#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`LockManager`** interface of the Web Locks API provides methods for requesting a new Lock object and querying for an existing `Lock` object.
/// Available only in secure contexts.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/LockManager)
/// </summary>
// Requires secure context (HTTPS).
public partial interface ILockManager
{
    /// <summary>
/// The **`query()`** method of the LockManager interface returns a Promise that resolves with an object containing information about held and pending locks.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/LockManager/query)
/// </summary>
[global::Microsoft.JSInterop.DomJavaScriptName("query")]
ValueTask<LockManagerSnapshot> QueryAsync();

    /// <summary>
/// The **`request()`** method of the LockManager interface requests a Lock object with parameters specifying its name and characteristics.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/LockManager/request)
/// </summary>
[global::Microsoft.JSInterop.DomJavaScriptName("request")]
ValueTask<T> RequestAsync<T>(string name, LockGrantedCallback<T> callback);

    [global::Microsoft.JSInterop.DomJavaScriptName("request")]
ValueTask<T> RequestAsync<T>(string name, LockOptions options, LockGrantedCallback<T> callback);
}
