// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`Attr`** interface represents one of an element's attributes as an object.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Attr)
/// </summary>
public partial interface IAttr : INode
{
    /// <summary>
    /// The read-only **`localName`** property of the Attr interface returns the _local part_ of the _qualified name_ of an attribute, that is the name of the attribute, stripped from any namespace in front of it.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Attr/localName)
    /// </summary>
    string LocalName { get; }
    /// <summary>
    /// The read-only **`name`** property of the Attr interface returns the _qualified name_ of an attribute, that is the name of the attribute, with the namespace prefix, if any, in front of it.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Attr/name)
    /// </summary>
    string Name { get; }
    // PROJECTION-FAILED: namespaceURI — Unsupported union type 'StringKeyword | null' at 'Attr.namespaceURI'. Mixed unions (non-nullable, non-all-string-literal
    IDocument OwnerDocument { get; }
    // PROJECTION-FAILED: ownerElement — Unsupported union type 'Element | null' at 'Attr.ownerElement'. Mixed unions (non-nullable, non-all-string-literal) cann
    // PROJECTION-FAILED: prefix — Unsupported union type 'StringKeyword | null' at 'Attr.prefix'. Mixed unions (non-nullable, non-all-string-literal) cann
    /// <summary>
    /// The read-only **`specified`** property of the Attr interface always returns `true`.
    /// </summary>
    [Obsolete]
    bool Specified { get; }
    /// <summary>
    /// The **`value`** property of the Attr interface contains the value of the attribute.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Attr/value)
    /// </summary>
    string Value { get; }
    /// <summary>
    /// [MDN Reference](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent)
    /// </summary>
    // DEFERRED: textContent — type resolves to 'void' (undefined/void in TypeScript)
}
