// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`CompressionStream`** interface of the Compression Streams API is an API for compressing a stream of data.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CompressionStream)
/// </summary>
public partial interface ICompressionStream : IGenericTransformStream
{
    System.IO.Stream Readable { get; }
    System.IO.Stream Writable { get; }
}
