#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`CountQueuingStrategy`** interface of the Streams API provides a built-in chunk counting queuing strategy that can be used when constructing streams.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CountQueuingStrategy)
/// </summary>
public partial interface ICountQueuingStrategy : IQueuingStrategyContract<object>, global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// The read-only **`CountQueuingStrategy.highWaterMark`** property returns the total number of chunks that can be contained in the internal queue before backpressure is applied.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CountQueuingStrategy/highWaterMark)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("highWaterMark", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
double HighWaterMark { get; }

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CountQueuingStrategy/size)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("size", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "QueuingStrategySize<any>", Nullable = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Callback type 'QueuingStrategySize' requires generated callback marshalling.")]
QueuingStrategySize<object> Size { get; }
}
