#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`CSSKeywordValue`** interface of the CSS Typed Object Model API creates an object to represent CSS keywords and other identifiers.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSKeywordValue)
/// </summary>
public partial interface ICSSKeywordValue : ICSSStyleValue, global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// The **`value`** property of the `CSSKeywordValue`.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSKeywordValue/value)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("value", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("value", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Value { get; set; }
}
