#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`CSSMathProduct`** interface of the CSS Typed Object Model API represents the result obtained by calling CSSNumericValue.add, CSSNumericValue.sub, or CSSNumericValue.toSum on CSSNumericValue.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSMathProduct)
/// </summary>
public partial interface ICSSMathProduct : ICSSMathValue, global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// The **`CSSMathProduct.values`** read-only property of the CSSMathProduct interface returns a A CSSNumericArray.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSMathProduct/values)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("values", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "CSSNumericArray", Nullable = false, Streamable = false, StructuredClone = false)]
ICSSNumericArray Values { get; }
}
