#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The `FileSystemDirectoryReader` interface of the File and Directory Entries API lets you access the FileSystemFileEntry-based objects (generally FileSystemFileEntry or FileSystemDirectoryEntry) representing each entry in a directory.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FileSystemDirectoryReader)
/// </summary>
public partial interface IFileSystemDirectoryReader : global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// The FileSystemDirectoryReader interface's **`readEntries()`** method retrieves the directory entries within the directory being read and delivers them in an array to a provided callback function.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FileSystemDirectoryReader/readEntries)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:readEntries`0<>(FileSystemEntriesCallback<>:optional=False:rest=False,ErrorCallback<>:optional=True:rest=False)[clr:FileSystemEntriesCallback,ErrorCallback]->void@transport:json-value:False:False:True:void", "readEntries", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void ReadEntries(FileSystemEntriesCallback successCallback, ErrorCallback? errorCallback = default);
}
