#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

// Requires secure context (HTTPS).
public partial interface IGPUAdapterInfo : global::Microsoft.JSInterop.IDomProxy
{
    [global::Microsoft.JSInterop.DomAccessor("__brand", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "\"GPUAdapterInfo\"", Nullable = false, Streamable = false, StructuredClone = true)]
global::Blazor.DOM.AdvancedTypes.GPUAdapterInfoStringShape_45021b2ef1 Brand { get; }

    /// <summary>
/// The name of the vendor of the adapter, if available. Empty string otherwise.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("vendor", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Vendor { get; }

    /// <summary>
/// The name of the family or class of GPUs the adapter belongs to, if available. Empty
/// string otherwise.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("architecture", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Architecture { get; }

    /// <summary>
/// A vendor-specific identifier for the adapter, if available. Empty string otherwise.
/// Note: This is a value that represents the type of adapter. For example, it may be a
/// [PCI device ID](https://pcisig.com/). It does not uniquely identify a given piece of
/// hardware like a serial number.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("device", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Device { get; }

    /// <summary>
/// A human readable string describing the adapter as reported by the driver, if available.
/// Empty string otherwise.
/// Note: Because no formatting is applied to {@link GPUAdapterInfo#description} attempting to parse
/// this value is not recommended. Applications which change their behavior based on the
/// {@link GPUAdapterInfo}, such as applying workarounds for known driver issues, should rely on the
/// other fields when possible.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("description", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Description { get; }

    /// <summary>
/// If the "subgroups" feature is supported, the minimum supported subgroup size for the
/// adapter.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("subgroupMinSize", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = true, Streamable = false, StructuredClone = true)]
double? SubgroupMinSize { get; }

    /// <summary>
/// If the "subgroups" feature is supported, the maximum supported subgroup size for the
/// adapter.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("subgroupMaxSize", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = true, Streamable = false, StructuredClone = true)]
double? SubgroupMaxSize { get; }

    /// <summary>
/// Whether the adapter is a fallback adapter.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("isFallbackAdapter", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
bool IsFallbackAdapter { get; }
}
