#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IGPURenderCommandsMixin : global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// Sets the current {@link GPURenderPipeline}.
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:setPipeline`0<>(GPURenderPipeline<>:optional=False:rest=False)[clr:IGPURenderPipeline]->global::Microsoft.JSInterop.BrowserUndefined@transport:none", "setPipeline", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "global::Microsoft.JSInterop.BrowserUndefined", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Source IR does not provide reviewed transport metadata.")]
global::Microsoft.JSInterop.BrowserUndefined SetPipeline(IGPURenderPipeline pipeline);

    /// <summary>
/// Sets the current index buffer.
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:setIndexBuffer`0<>(GPUBuffer<>:optional=False:rest=False,GPUIndexFormat<>:optional=False:rest=False,GPUSize64<>:optional=True:rest=False,GPUSize64<>:optional=True:rest=False)[clr:IGPUBuffer,GPUIndexFormat,double,double]->global::Microsoft.JSInterop.BrowserUndefined@transport:none", "setIndexBuffer", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "global::Microsoft.JSInterop.BrowserUndefined", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Source IR does not provide reviewed transport metadata.")]
global::Microsoft.JSInterop.BrowserUndefined SetIndexBuffer(IGPUBuffer buffer, GPUIndexFormat indexFormat, double offset = default, double size = default);

    /// <summary>
/// Sets the current vertex buffer for the given slot.
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:setVertexBuffer`0<>(GPUIndex32<>:optional=False:rest=False,union(GPUBuffer<>|NullKeyword:null|UndefinedKeyword):optional=False:rest=False,GPUSize64<>:optional=True:rest=False,GPUSize64<>:optional=True:rest=False)[clr:double,global::Blazor.DOM.AdvancedTypes.GPURenderCommandsMixinUnionShape_84cea639c9,double,double]->global::Microsoft.JSInterop.BrowserUndefined@transport:none", "setVertexBuffer", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "global::Microsoft.JSInterop.BrowserUndefined", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Source IR does not provide reviewed transport metadata.")]
global::Microsoft.JSInterop.BrowserUndefined SetVertexBuffer(double slot, global::Blazor.DOM.AdvancedTypes.GPURenderCommandsMixinUnionShape_84cea639c9 buffer, double offset = default, double size = default);

    /// <summary>
/// Draws primitives.
/// See {@link https://www.w3.org/TR/webgpu/#rendering-operations} for the detailed specification.
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:draw`0<>(GPUSize32<>:optional=False:rest=False,GPUSize32<>:optional=True:rest=False,GPUSize32<>:optional=True:rest=False,GPUSize32<>:optional=True:rest=False)[clr:double,double,double,double]->global::Microsoft.JSInterop.BrowserUndefined@transport:none", "draw", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "global::Microsoft.JSInterop.BrowserUndefined", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Source IR does not provide reviewed transport metadata.")]
global::Microsoft.JSInterop.BrowserUndefined Draw(double vertexCount, double instanceCount = default, double firstVertex = default, double firstInstance = default);

    /// <summary>
/// Draws indexed primitives.
/// See {@link https://www.w3.org/TR/webgpu/#rendering-operations} for the detailed specification.
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:drawIndexed`0<>(GPUSize32<>:optional=False:rest=False,GPUSize32<>:optional=True:rest=False,GPUSize32<>:optional=True:rest=False,GPUSignedOffset32<>:optional=True:rest=False,GPUSize32<>:optional=True:rest=False)[clr:double,double,double,double,double]->global::Microsoft.JSInterop.BrowserUndefined@transport:none", "drawIndexed", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "global::Microsoft.JSInterop.BrowserUndefined", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Source IR does not provide reviewed transport metadata.")]
global::Microsoft.JSInterop.BrowserUndefined DrawIndexed(double indexCount, double instanceCount = default, double firstIndex = default, double baseVertex = default, double firstInstance = default);

    /// <summary>
/// Draws primitives using parameters read from a {@link GPUBuffer}.
/// See {@link https://www.w3.org/TR/webgpu/#rendering-operations} for the detailed specification.
/// packed block of **four 32-bit unsigned integer values (16 bytes total)**, given in the same
/// order as the arguments for {@link GPURenderCommandsMixin#draw}. For example:
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:drawIndirect`0<>(GPUBuffer<>:optional=False:rest=False,GPUSize64<>:optional=False:rest=False)[clr:IGPUBuffer,double]->global::Microsoft.JSInterop.BrowserUndefined@transport:none", "drawIndirect", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "global::Microsoft.JSInterop.BrowserUndefined", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Source IR does not provide reviewed transport metadata.")]
global::Microsoft.JSInterop.BrowserUndefined DrawIndirect(IGPUBuffer indirectBuffer, double indirectOffset);

    /// <summary>
/// Draws indexed primitives using parameters read from a {@link GPUBuffer}.
/// See {@link https://www.w3.org/TR/webgpu/#rendering-operations} for the detailed specification.
/// tightly packed block of **five 32-bit unsigned integer values (20 bytes total)**, given in
/// the same order as the arguments for {@link GPURenderCommandsMixin#drawIndexed}. For example:
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:drawIndexedIndirect`0<>(GPUBuffer<>:optional=False:rest=False,GPUSize64<>:optional=False:rest=False)[clr:IGPUBuffer,double]->global::Microsoft.JSInterop.BrowserUndefined@transport:none", "drawIndexedIndirect", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "global::Microsoft.JSInterop.BrowserUndefined", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Source IR does not provide reviewed transport metadata.")]
global::Microsoft.JSInterop.BrowserUndefined DrawIndexedIndirect(IGPUBuffer indirectBuffer, double indirectOffset);
}
