#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`HTMLTrackElement`** interface represents an HTML track element within the DOM.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLTrackElement)
/// </summary>
[global::Microsoft.JSInterop.DomEventTarget("HTMLTrackElement", "HTMLElementEventMap")]
public partial interface IHTMLTrackElement : IHTMLElement, global::Microsoft.JSInterop.IDomEventTargetProxy
{
    /// <summary>
/// The **`default`** property of the HTMLTrackElement interface represents whether the track will be enabled if the user's preferences do not indicate that another track would be more appropriate.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLTrackElement/default)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("default", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("default", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
bool Default { get; set; }

    /// <summary>
/// The **`kind`** property of the HTMLTrackElement interface represents the type of track, or how the text track is meant to be used.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLTrackElement/kind)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("kind", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("kind", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Kind { get; set; }

    /// <summary>
/// The **`label`** property of the HTMLTrackElement represents the user-readable title displayed when listing subtitle, caption, and audio descriptions for a track.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLTrackElement/label)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("label", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("label", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Label { get; set; }

    /// <summary>
/// The **`readyState`** read-only property of the HTMLTrackElement interface returns a number representing the track element's text track readiness state: 0.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLTrackElement/readyState)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("readyState", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
double ReadyState { get; }

    /// <summary>
/// The **`src`** property of the HTMLTrackElement interface reflects the value of the track element's `src` attribute, which indicates the URL of the text track's data.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLTrackElement/src)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("src", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("src", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Src { get; set; }

    /// <summary>
/// The **`srclang`** property of the HTMLTrackElement interface reflects the value of the track element's `srclang` attribute or the empty string if not defined.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLTrackElement/srclang)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("srclang", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("srclang", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Srclang { get; set; }

    /// <summary>
/// The **`track`** read-only property of the HTMLTrackElement interface returns a TextTrack object corresponding to the text track of the track element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLTrackElement/track)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("track", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "TextTrack", Nullable = false, Streamable = false, StructuredClone = false)]
ITextTrack Track { get; }

    [global::Microsoft.JSInterop.DomAccessor("NONE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "0", Nullable = false, Streamable = false, StructuredClone = true)]
double NONE { get; }

    [global::Microsoft.JSInterop.DomAccessor("LOADING", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "1", Nullable = false, Streamable = false, StructuredClone = true)]
double LOADING { get; }

    [global::Microsoft.JSInterop.DomAccessor("LOADED", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "2", Nullable = false, Streamable = false, StructuredClone = true)]
double LOADED { get; }

    [global::Microsoft.JSInterop.DomAccessor("ERROR", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "3", Nullable = false, Streamable = false, StructuredClone = true)]
double ERROR { get; }

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void AddEventListener(string type, EventListenerOrEventListenerObject listener);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void AddEventListener(string type, EventListenerOrEventListenerObject listener, bool capture);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,AddEventListenerOptions]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void AddEventListener(string type, EventListenerOrEventListenerObject listener, AddEventListenerOptions? options);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void RemoveEventListener(string type, EventListenerOrEventListenerObject listener);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, bool capture);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,EventListenerOptions]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, EventListenerOptions? options);
}
