#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`IntersectionObserver`** interface of the Intersection Observer API provides a way to asynchronously observe changes in the intersection of a target element with an ancestor element or with a top-level document's viewport.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver)
/// </summary>
public partial interface IIntersectionObserver : global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// The IntersectionObserver interface's read-only **`root`** property identifies the Element or of the viewport for the element which is the observer's target.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/root)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("root", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "Element | Document | null", Nullable = true, Streamable = false, StructuredClone = false)]
global::Blazor.DOM.AdvancedTypes.IntersectionObserverUnionShape_e86cd39766 Root { get; }

    /// <summary>
/// The IntersectionObserver interface's read-only **`rootMargin`** property is a string with syntax similar to that of the CSS margin property.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/rootMargin)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("rootMargin", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string RootMargin { get; }

    /// <summary>
/// The IntersectionObserver interface's read-only **`thresholds`** property returns the list of intersection thresholds that was specified when the observer was instantiated with only one threshold ratio was provided when instantiating the object, this will be an array containing that single value.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/thresholds)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("thresholds", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "readonly number[]", Nullable = false, Streamable = false, StructuredClone = true)]
double[] Thresholds { get; }

    /// <summary>
/// The IntersectionObserver method **`disconnect()`** stops watching all of its target elements for visibility changes.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/disconnect)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:disconnect`0<>()[clr:]->void@transport:json-value:False:False:True:void", "disconnect", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void Disconnect();

    /// <summary>
/// The IntersectionObserver method **`observe()`** adds an element to the set of target elements being watched by the `IntersectionObserver`.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/observe)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:observe`0<>(Element<>:optional=False:rest=False)[clr:IElement]->void@transport:json-value:False:False:True:void", "observe", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void Observe(IElement target);

    /// <summary>
/// The IntersectionObserver method **`takeRecords()`** returns an array of has experienced an intersection change since the last time the intersections were checked, either explicitly through a call to this method or implicitly by an automatic call to the observer's callback.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/takeRecords)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:takeRecords`0<>()[clr:]->global::Microsoft.JSInterop.IBrowserArray<IIntersectionObserverEntry>@transport:js-reference:False:False:False:IntersectionObserverEntry[]", "takeRecords", global::Microsoft.JSInterop.DomTransportKind.JsReference, "IntersectionObserverEntry[]", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
global::Microsoft.JSInterop.IBrowserArray<IIntersectionObserverEntry> TakeRecords();

    /// <summary>
/// The IntersectionObserver method **`unobserve()`** instructs the `IntersectionObserver` to stop observing the specified target element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/IntersectionObserver/unobserve)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:unobserve`0<>(Element<>:optional=False:rest=False)[clr:IElement]->void@transport:json-value:False:False:True:void", "unobserve", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
void Unobserve(IElement target);
}
