// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`MessagePort`** interface of the Channel Messaging API represents one of the two ports of a MessageChannel, allowing messages to be sent from one port and listening out for them arriving at the other.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessagePort)
/// </summary>
// Transferable (supports postMessage transfer).
public partial interface IMessagePort : IEventTarget, IMessageEventTarget
{
    /// <summary>
    /// The **`close()`** method of the MessagePort interface disconnects the port, so it is no longer active.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessagePort/close)
    /// </summary>
    void Close();

    /// <summary>
    /// The **`postMessage()`** method of the transfers ownership of objects to other browsing contexts.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessagePort/postMessage)
    /// </summary>
    void PostMessage(object message, Transferable[] transfer);

    void PostMessage(object message, StructuredSerializeOptions options = default);

    /// <summary>
    /// The **`start()`** method of the MessagePort interface starts the sending of messages queued on the port.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessagePort/start)
    /// </summary>
    void Start();

    void AddEventListener(object type, object listener, object options = default);

    void AddEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);

    void RemoveEventListener(object type, object listener, object options = default);

    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);
}
