#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`NamedNodeMap`** interface represents a collection of Attr objects.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NamedNodeMap)
/// </summary>
public partial interface INamedNodeMap : global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// The read-only **`length`** property of the NamedNodeMap interface is the number of objects stored in the map.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NamedNodeMap/length)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("length", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
double Length { get; }

    [global::Microsoft.JSInterop.DomIndexAccessor(global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomIndexKeyKind.Number, "number", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Attr", Nullable = false, Streamable = false, StructuredClone = false)]
IAttr GetIndexedValueByNumber(double index);
[global::Microsoft.JSInterop.DomIndexAccessor(global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomIndexKeyKind.Number, "number", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Attr", Nullable = false, Streamable = false, StructuredClone = false)]
void SetIndexedValueByNumber(double index, IAttr value);

    /// <summary>
/// The **`getNamedItem()`** method of the NamedNodeMap interface returns the Attr corresponding to the given name, or `null` if there is no corresponding attribute.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NamedNodeMap/getNamedItem)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:getNamedItem`0<>(StringKeyword:optional=False:rest=False)[clr:string]->IAttr@transport:js-reference:True:False:False:Attr | null", "getNamedItem", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Attr | null", Nullable = true, Promise = false, Streamable = false, StructuredClone = false)]
IAttr? GetNamedItem(string qualifiedName);

    /// <summary>
/// The **`getNamedItemNS()`** method of the NamedNodeMap interface returns the Attr corresponding to the given local name in the given namespace, or `null` if there is no corresponding attribute.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NamedNodeMap/getNamedItemNS)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:getNamedItemNS`0<>(union(StringKeyword|NullKeyword:null):optional=False:rest=False,StringKeyword:optional=False:rest=False)[clr:string,string]->IAttr@transport:js-reference:True:False:False:Attr | null", "getNamedItemNS", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Attr | null", Nullable = true, Promise = false, Streamable = false, StructuredClone = false)]
IAttr? GetNamedItemNS(string? @namespace, string localName);

    /// <summary>
/// The **`item()`** method of the NamedNodeMap interface returns the item in the map matching the index.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NamedNodeMap/item)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:item`0<>(NumberKeyword:optional=False:rest=False)[clr:double]->IAttr@transport:js-reference:True:False:False:Attr | null", "item", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Attr | null", Nullable = true, Promise = false, Streamable = false, StructuredClone = false)]
IAttr? Item(double index);

    /// <summary>
/// The **`removeNamedItem()`** method of the NamedNodeMap interface removes the Attr corresponding to the given name from the map.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NamedNodeMap/removeNamedItem)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:removeNamedItem`0<>(StringKeyword:optional=False:rest=False)[clr:string]->IAttr@transport:js-reference:False:False:False:Attr", "removeNamedItem", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Attr", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
IAttr RemoveNamedItem(string qualifiedName);

    /// <summary>
/// The **`removeNamedItemNS()`** method of the NamedNodeMap interface removes the Attr corresponding to the given namespace and local name from the map.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NamedNodeMap/removeNamedItemNS)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:removeNamedItemNS`0<>(union(StringKeyword|NullKeyword:null):optional=False:rest=False,StringKeyword:optional=False:rest=False)[clr:string,string]->IAttr@transport:js-reference:False:False:False:Attr", "removeNamedItemNS", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Attr", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
IAttr RemoveNamedItemNS(string? @namespace, string localName);

    /// <summary>
/// The **`setNamedItem()`** method of the NamedNodeMap interface puts the Attr identified by its name in the map.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NamedNodeMap/setNamedItem)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:setNamedItem`0<>(Attr<>:optional=False:rest=False)[clr:IAttr]->IAttr@transport:js-reference:True:False:False:Attr | null", "setNamedItem", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Attr | null", Nullable = true, Promise = false, Streamable = false, StructuredClone = false)]
IAttr? SetNamedItem(IAttr attr);

    /// <summary>
/// The **`setNamedItemNS()`** method of the NamedNodeMap interface puts the Attr identified by its name in the map.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NamedNodeMap/setNamedItemNS)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:setNamedItemNS`0<>(Attr<>:optional=False:rest=False)[clr:IAttr]->IAttr@transport:js-reference:True:False:False:Attr | null", "setNamedItemNS", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Attr | null", Nullable = true, Promise = false, Streamable = false, StructuredClone = false)]
IAttr? SetNamedItemNS(IAttr attr);

    [global::Microsoft.JSInterop.DomOperation("js:Symbol.iterator`0<>()[clr:]->global::Microsoft.JSInterop.IBrowserIterableIterator<IAttr>@transport:js-reference:False:False:False:ArrayIterator<Attr>", "Symbol.iterator", global::Microsoft.JSInterop.DomTransportKind.JsReference, "ArrayIterator<Attr>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
[global::Microsoft.JSInterop.DomSymbol(global::Microsoft.JSInterop.DomWellKnownSymbol.Iterator)]
global::Microsoft.JSInterop.IBrowserIterableIterator<IAttr> SymbolIterator();
}
