#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// Available only in secure contexts.
/// </summary>
// Requires secure context (HTTPS).
public partial interface INavigatorLocks : global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Navigator/locks)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("locks", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "LockManager", Nullable = false, Streamable = false, StructuredClone = false)]
ILockManager Locks { get; }
}
