#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`OES_element_index_uint`** extension is part of the WebGL API and adds support for `gl.UNSIGNED_INT` types to WebGLRenderingContext.drawElements().
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/OES_element_index_uint)
/// </summary>
public partial interface IOES_element_index_uint : global::Microsoft.JSInterop.IDomProxy
{
}
