#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IPropertyIndexedKeyframes : global::Microsoft.JSInterop.IDomProxy
{
    [global::Microsoft.JSInterop.DomAccessor("composite", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CompositeOperationOrAuto | CompositeOperationOrAuto[]", Nullable = true, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("composite", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CompositeOperationOrAuto | CompositeOperationOrAuto[]", Nullable = true, Streamable = false, StructuredClone = true)]
global::Blazor.DOM.AdvancedTypes.PropertyIndexedKeyframesUnionShape_813a70da30? Composite { get; set; }

    [global::Microsoft.JSInterop.DomAccessor("easing", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string | string[]", Nullable = true, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("easing", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string | string[]", Nullable = true, Streamable = false, StructuredClone = true)]
global::Blazor.DOM.AdvancedTypes.ConstrainDOMStringParametersUnionShape_5033fa5046? Easing { get; set; }

    [global::Microsoft.JSInterop.DomAccessor("offset", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | (number | null)[]", Nullable = true, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("offset", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | (number | null)[]", Nullable = true, Streamable = false, StructuredClone = true)]
global::Blazor.DOM.AdvancedTypes.PropertyIndexedKeyframesUnionShape_62d7ae8405? Offset { get; set; }

    [global::Microsoft.JSInterop.DomIndexAccessor(global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomIndexKeyKind.String, "string", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string | number | string[] | (number | null)[] | null | undefined", Nullable = true, Streamable = false, StructuredClone = true)]
global::Blazor.DOM.AdvancedTypes.PropertyIndexedKeyframesUnionShape_c4348e4da6 GetIndexedValueByString(string property);
[global::Microsoft.JSInterop.DomIndexAccessor(global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomIndexKeyKind.String, "string", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string | number | string[] | (number | null)[] | null | undefined", Nullable = true, Streamable = false, StructuredClone = true)]
void SetIndexedValueByString(string property, global::Blazor.DOM.AdvancedTypes.PropertyIndexedKeyframesUnionShape_c4348e4da6 value);
}
