#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The WebRTC API interface **`RTCTrackEvent`** represents the RTCPeerConnection.track_event event, which is sent when a new MediaStreamTrack is added to an RTCRtpReceiver which is part of the RTCPeerConnection.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCTrackEvent)
/// </summary>
public partial interface IRTCTrackEvent : IEvent, global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// The read-only **`receiver`** property of the RTCTrackEvent interface indicates the The RTCRtpReceiver which pairs the `receiver` with a sender and other properties which establish a single bidirectional RTP stream for use by the RTCTrackEvent.track associated with the `RTCTrackEvent`.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCTrackEvent/receiver)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("receiver", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "RTCRtpReceiver", Nullable = false, Streamable = false, StructuredClone = false)]
IRTCRtpReceiver Receiver { get; }

    /// <summary>
/// The WebRTC API interface RTCTrackEvent's read-only **`streams`** property specifies an array of track being added to the RTCPeerConnection.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCTrackEvent/streams)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("streams", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "readonly MediaStream[]", Nullable = false, Streamable = false, StructuredClone = false)]
global::Microsoft.JSInterop.IReadOnlyBrowserArray<IMediaStream> Streams { get; }

    /// <summary>
/// The
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCTrackEvent/track)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("track", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "MediaStreamTrack", Nullable = false, Streamable = false, StructuredClone = false)]
IMediaStreamTrack Track { get; }

    /// <summary>
/// The WebRTC API interface RTCTrackEvent's read-only **`transceiver`** property indicates the The transceiver pairs the track's The RTCRtpTransceiver which pairs the `receiver` with a sender and other properties which establish a single bidirectional RTP stream for use by the RTCTrackEvent.track associated with the `RTCTrackEvent`.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCTrackEvent/transceiver)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("transceiver", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "RTCRtpTransceiver", Nullable = false, Streamable = false, StructuredClone = false)]
IRTCRtpTransceiver Transceiver { get; }
}
