#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The `StyleSheetList` interface represents a list of CSSStyleSheet objects.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/StyleSheetList)
/// </summary>
public partial interface IStyleSheetList : global::Microsoft.JSInterop.IDomProxy
{
    /// <summary>
/// The **`length`** read-only property of the StyleSheetList interface returns the number of CSSStyleSheet objects in the collection.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/StyleSheetList/length)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("length", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
double Length { get; }

    [global::Microsoft.JSInterop.DomIndexAccessor(global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomIndexKeyKind.Number, "number", global::Microsoft.JSInterop.DomTransportKind.JsReference, "CSSStyleSheet", Nullable = false, Streamable = false, StructuredClone = false)]
ICSSStyleSheet GetIndexedValueByNumber(double index);
[global::Microsoft.JSInterop.DomIndexAccessor(global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomIndexKeyKind.Number, "number", global::Microsoft.JSInterop.DomTransportKind.JsReference, "CSSStyleSheet", Nullable = false, Streamable = false, StructuredClone = false)]
void SetIndexedValueByNumber(double index, ICSSStyleSheet value);

    /// <summary>
/// The **`item()`** method of the StyleSheetList interface returns a single CSSStyleSheet object.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/StyleSheetList/item)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:item`0<>(NumberKeyword:optional=False:rest=False)[clr:double]->ICSSStyleSheet@transport:js-reference:True:False:False:CSSStyleSheet | null", "item", global::Microsoft.JSInterop.DomTransportKind.JsReference, "CSSStyleSheet | null", Nullable = true, Promise = false, Streamable = false, StructuredClone = false)]
ICSSStyleSheet? Item(double index);

    [global::Microsoft.JSInterop.DomOperation("js:Symbol.iterator`0<>()[clr:]->global::Microsoft.JSInterop.IBrowserIterableIterator<ICSSStyleSheet>@transport:js-reference:False:False:False:ArrayIterator<CSSStyleSheet>", "Symbol.iterator", global::Microsoft.JSInterop.DomTransportKind.JsReference, "ArrayIterator<CSSStyleSheet>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
[global::Microsoft.JSInterop.DomSymbol(global::Microsoft.JSInterop.DomWellKnownSymbol.Iterator)]
global::Microsoft.JSInterop.IBrowserIterableIterator<ICSSStyleSheet> SymbolIterator();
}
