#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SVGUnitTypes`** interface defines a commonly used set of constants used for reflecting gradientUnits, patternContentUnits and other similar attributes.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGUnitTypes)
/// </summary>
public partial interface ISVGUnitTypes : global::Microsoft.JSInterop.IDomProxy
{
    [global::Microsoft.JSInterop.DomAccessor("SVG_UNIT_TYPE_UNKNOWN", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "0", Nullable = false, Streamable = false, StructuredClone = true)]
double SVGUNITTYPEUNKNOWN { get; }

    [global::Microsoft.JSInterop.DomAccessor("SVG_UNIT_TYPE_USERSPACEONUSE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "1", Nullable = false, Streamable = false, StructuredClone = true)]
double SVGUNITTYPEUSERSPACEONUSE { get; }

    [global::Microsoft.JSInterop.DomAccessor("SVG_UNIT_TYPE_OBJECTBOUNDINGBOX", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "2", Nullable = false, Streamable = false, StructuredClone = true)]
double SVGUNITTYPEOBJECTBOUNDINGBOX { get; }
}
