// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`Touch`** interface represents a single contact point on a touch-sensitive device.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch)
/// </summary>
public partial interface ITouch
{
    /// <summary>
    /// The `Touch.clientX` read-only property returns the X coordinate of the touch point relative to the viewport, not including any scroll offset.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/clientX)
    /// </summary>
    double ClientX { get; }
    /// <summary>
    /// The **`Touch.clientY`** read-only property returns the Y coordinate of the touch point relative to the browser's viewport, not including any scroll offset.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/clientY)
    /// </summary>
    double ClientY { get; }
    /// <summary>
    /// The **`Touch.force`** read-only property returns the amount of pressure the user is applying to the touch surface for a Touch point.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/force)
    /// </summary>
    double Force { get; }
    /// <summary>
    /// The **`Touch.identifier`** returns a value uniquely identifying this point of contact with the touch surface.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/identifier)
    /// </summary>
    double Identifier { get; }
    /// <summary>
    /// The **`Touch.pageX`** read-only property returns the X coordinate of the touch point relative to the viewport, including any scroll offset.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/pageX)
    /// </summary>
    double PageX { get; }
    /// <summary>
    /// The **`Touch.pageY`** read-only property returns the Y coordinate of the touch point relative to the viewport, including any scroll offset.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/pageY)
    /// </summary>
    double PageY { get; }
    /// <summary>
    /// The **`radiusX`** read-only property of the Touch interface returns the X radius of the ellipse that most closely circumscribes the area of contact with the touch surface.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/radiusX)
    /// </summary>
    double RadiusX { get; }
    /// <summary>
    /// The **`radiusY`** read-only property of the Touch interface returns the Y radius of the ellipse that most closely circumscribes the area of contact with the touch surface.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/radiusY)
    /// </summary>
    double RadiusY { get; }
    /// <summary>
    /// The **`rotationAngle`** read-only property of the Touch interface returns the rotation angle, in degrees, of the contact area ellipse defined by Touch.radiusX and Touch.radiusY.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/rotationAngle)
    /// </summary>
    double RotationAngle { get; }
    /// <summary>
    /// Returns the X coordinate of the touch point relative to the screen, not including any scroll offset.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/screenX)
    /// </summary>
    double ScreenX { get; }
    /// <summary>
    /// Returns the Y coordinate of the touch point relative to the screen, not including any scroll offset.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/screenY)
    /// </summary>
    double ScreenY { get; }
    /// <summary>
    /// The read-only **`target`** property of the `Touch` interface returns the (EventTarget) on which the touch contact started when it was first placed on the surface, even if the touch point has since moved outside the interactive area of that element or even been removed from the document.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Touch/target)
    /// </summary>
    IEventTarget Target { get; }
}
