#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IEventFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    global::System.Threading.Tasks.ValueTask<IEvent> GetPrototypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<IEvent>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IEvent>("prototype"), cancellationToken);
    global::System.Threading.Tasks.ValueTask SetPrototypeAsync(IEvent value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value, cancellationToken);

    global::System.Threading.Tasks.ValueTask<IEvent> CreateAsync(string type, EventInit? eventInitDict = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.ConstructAsync<IEvent>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "Event", [type, eventInitDict], cancellationToken);

    global::System.Threading.Tasks.ValueTask<double> GetNONEAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "NONE", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("NONE"), cancellationToken);

    global::System.Threading.Tasks.ValueTask<double> GetCAPTURINGPHASEAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "CAPTURING_PHASE", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("CAPTURING_PHASE"), cancellationToken);

    global::System.Threading.Tasks.ValueTask<double> GetATTARGETAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "AT_TARGET", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("AT_TARGET"), cancellationToken);

    global::System.Threading.Tasks.ValueTask<double> GetBUBBLINGPHASEAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "BUBBLING_PHASE", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("BUBBLING_PHASE"), cancellationToken);
}


public sealed class EventFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IEventFactory
{
}
