// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`AnimationEvent`** interface represents events providing information related to animations.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AnimationEvent)
/// </summary>
public partial interface IAnimationEvent : IEvent
{
    /// <summary>
    /// The **`AnimationEvent.animationName`** read-only property is a string containing the value of the animation-name CSS property associated with the transition.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AnimationEvent/animationName)
    /// </summary>
    string AnimationName { get; }
    /// <summary>
    /// The **`AnimationEvent.elapsedTime`** read-only property is a `float` giving the amount of time the animation has been running, in seconds, when this event fired, excluding any time the animation was paused.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AnimationEvent/elapsedTime)
    /// </summary>
    double ElapsedTime { get; }
    /// <summary>
    /// The **`AnimationEvent.pseudoElement`** read-only property is a string, starting with `'::'`, containing the name of the pseudo-element the animation runs on.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AnimationEvent/pseudoElement)
    /// </summary>
    string PseudoElement { get; }
}
