// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`CSSFontPaletteValuesRule`** interface represents an
/// </summary>
public partial interface ICSSFontPaletteValuesRule : ICSSRule
{
    /// <summary>
    /// The read-only **`basePalette`** property of the CSSFontPaletteValuesRule interface indicates the base palette associated with the rule.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontPaletteValuesRule/basePalette)
    /// </summary>
    string BasePalette { get; }
    /// <summary>
    /// The read-only **`fontFamily`** property of the CSSFontPaletteValuesRule interface lists the font families the rule can be applied to.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontPaletteValuesRule/fontFamily)
    /// </summary>
    string FontFamily { get; }
    /// <summary>
    /// The read-only **`name`** property of the CSSFontPaletteValuesRule interface represents the name identifying the associated
    /// </summary>
    string Name { get; }
    /// <summary>
    /// The read-only **`overrideColors`** property of the CSSFontPaletteValuesRule interface is a string containing a list of color index and color pair that are to be used instead.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontPaletteValuesRule/overrideColors)
    /// </summary>
    string OverrideColors { get; }
}
