// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`FontFaceSetLoadEvent`** interface of the CSS Font Loading API represents events fired at a FontFaceSet after it starts loading font faces.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontFaceSetLoadEvent)
/// </summary>
public partial interface IFontFaceSetLoadEvent : IEvent
{
    /// <summary>
    /// The **`fontfaces`** read-only property of the An array of FontFace instance.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontFaceSetLoadEvent/fontfaces)
    /// </summary>
    IFontFace[] Fontfaces { get; }
}
