// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`HTMLOptGroupElement`** interface provides special properties and methods (beyond the regular HTMLElement object interface they also have available to them by inheritance) for manipulating the layout and presentation of optgroup elements.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLOptGroupElement)
/// </summary>
public partial interface IHTMLOptGroupElement : IHTMLElement
{
    /// <summary>
    /// The **`disabled`** property of the HTMLOptGroupElement interface is a boolean value that reflects the optgroup element's `disabled` attribute, which indicates whether the control is disabled.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLOptGroupElement/disabled)
    /// </summary>
    bool Disabled { get; }
    /// <summary>
    /// The **`label`** property of the HTMLOptGroupElement interface is a string value that reflects the optgroup element's `label` attribute, which provides a textual label to the group of options.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLOptGroupElement/label)
    /// </summary>
    string Label { get; }

    void AddEventListener(object type, object listener, object options = default);

    void AddEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);

    void RemoveEventListener(object type, object listener, object options = default);

    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);
}
