// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SpeechSynthesis`** interface of the Web Speech API is the controller interface for the speech service; this can be used to retrieve information about the synthesis voices available on the device, start and pause speech, and other commands besides.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechSynthesis)
/// </summary>
public partial interface ISpeechSynthesis : IEventTarget
{
    // PROJECTION-FAILED: onvoiceschanged — Unsupported union type 'parenthesized | null' at 'SpeechSynthesis.onvoiceschanged'. Mixed unions (non-nullable, non-all-
    /// <summary>
    /// The **`paused`** read-only property of the `true` if the `SpeechSynthesis` object is in a paused state, or `false` if not.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechSynthesis/paused)
    /// </summary>
    bool Paused { get; }
    /// <summary>
    /// The **`pending`** read-only property of the `true` if the utterance queue contains as-yet-unspoken utterances.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechSynthesis/pending)
    /// </summary>
    bool Pending { get; }
    /// <summary>
    /// The **`speaking`** read-only property of the `true` if an utterance is currently in the process of being spoken — even if `SpeechSynthesis` is in a A boolean value.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechSynthesis/speaking)
    /// </summary>
    bool Speaking { get; }

    /// <summary>
    /// The **`cancel()`** method of the SpeechSynthesis interface removes all utterances from the utterance queue.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechSynthesis/cancel)
    /// </summary>
    void Cancel();

    /// <summary>
    /// The **`getVoices()`** method of the current device.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechSynthesis/getVoices)
    /// </summary>
    ISpeechSynthesisVoice[] GetVoices();

    /// <summary>
    /// The **`pause()`** method of the SpeechSynthesis interface puts the `SpeechSynthesis` object into a paused state.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechSynthesis/pause)
    /// </summary>
    void Pause();

    /// <summary>
    /// The **`resume()`** method of the SpeechSynthesis interface puts the `SpeechSynthesis` object into a non-paused state: resumes it if it was already paused.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechSynthesis/resume)
    /// </summary>
    void Resume();

    /// <summary>
    /// The **`speak()`** method of the SpeechSynthesis interface adds an SpeechSynthesisUtterance to the utterance queue; it will be spoken when any other utterances queued before it have been spoken.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SpeechSynthesis/speak)
    /// </summary>
    void Speak(ISpeechSynthesisUtterance utterance);

    void AddEventListener(object type, object listener, object options = default);

    void AddEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);

    void RemoveEventListener(object type, object listener, object options = default);

    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);
}
