// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SubmitEvent`** interface defines the object used to represent an HTML form's HTMLFormElement.submit_event event.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SubmitEvent)
/// </summary>
public partial interface ISubmitEvent : IEvent
{
    // PROJECTION-FAILED: submitter — Unsupported union type 'HTMLElement | null' at 'SubmitEvent.submitter'. Mixed unions (non-nullable, non-all-string-liter
}
