// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SVGTransformList`** interface defines a list of SVGTransform objects.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList)
/// </summary>
public partial interface ISVGTransformList
{
    /// <summary>
    /// The **`length`** read-only property of the SVGTransformList interface represents the number of items in the list.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/length)
    /// </summary>
    double Length { get; }
    /// <summary>
    /// The **`numberOfItems`** read-only property of the SVGTransformList interface represents the number of items in the list.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/numberOfItems)
    /// </summary>
    double NumberOfItems { get; }

    /// <summary>
    /// The `appendItem()` method of the SVGTransformList interface inserts a new item at the end of the list.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/appendItem)
    /// </summary>
    ISVGTransform AppendItem(ISVGTransform newItem);

    /// <summary>
    /// The `clear()` method of the SVGTransformList interface clears all existing current items from the list, with the result being an empty list.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/clear)
    /// </summary>
    void Clear();

    // PROJECTION-FAILED: consolidate() return — Unsupported union type 'SVGTransform | null' at 'SVGTransformList.consolidate/return'. Mixed unions (non-nullable, non-a

    /// <summary>
    /// The `createSVGTransformFromMatrix()` method of the SVGTransformList interface creates an SVGTransform object which is initialized to a transform of type `SVG_TRANSFORM_MATRIX` and whose values are the given matrix.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/createSVGTransformFromMatrix)
    /// </summary>
    ISVGTransform CreateSVGTransformFromMatrix(DOMMatrix2DInit matrix = default);

    /// <summary>
    /// The `getItem()` method of the SVGTransformList interface returns the specified item from the list.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/getItem)
    /// </summary>
    ISVGTransform GetItem(double index);

    /// <summary>
    /// The `initialize()` method of the SVGTransformList interface clears all existing current items from the list and re-initializes the list to hold the single item specified by the parameter.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/initialize)
    /// </summary>
    ISVGTransform Initialize(ISVGTransform newItem);

    /// <summary>
    /// The `insertItemBefore()` method of the SVGTransformList interface inserts a new item into the list at the specified position.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/insertItemBefore)
    /// </summary>
    ISVGTransform InsertItemBefore(ISVGTransform newItem, double index);

    /// <summary>
    /// The `removeItem()` method of the SVGTransformList interface removes an existing item from the list.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/removeItem)
    /// </summary>
    ISVGTransform RemoveItem(double index);

    /// <summary>
    /// The `replaceItem()` method of the SVGTransformList interface replaces an existing item in the list with a new item.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/replaceItem)
    /// </summary>
    ISVGTransform ReplaceItem(ISVGTransform newItem, double index);

    // DEFERRED: 1 index signature(s) — deferred to index-accessor phase.
}
