// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SVGSymbolElement`** interface corresponds to the symbol element.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGSymbolElement)
/// </summary>
public partial interface ISVGSymbolElement : ISVGElement, ISVGFitToViewBox
{
    void AddEventListener(object type, object listener, object options = default);

    void AddEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);

    void RemoveEventListener(object type, object listener, object options = default);

    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);
}
