// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SVGPolygonElement`** interface provides access to the properties of polygon elements, as well as methods to manipulate them.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGPolygonElement)
/// </summary>
public partial interface ISVGPolygonElement : ISVGGeometryElement, ISVGAnimatedPoints
{
    void AddEventListener(object type, object listener, object options = default);

    void AddEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);

    void RemoveEventListener(object type, object listener, object options = default);

    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);
}
