// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// An **`XSLTProcessor`** applies an XSLT stylesheet transformation to an XML document to produce a new XML document as output.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/XSLTProcessor)
/// </summary>
public partial interface IXSLTProcessor
{
    /// <summary>
    /// The `clearParameters()` method of the XSLTProcessor interface removes all parameters (`&lt;xsl:param&gt;`) and their values from the stylesheet imported in the processor.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/XSLTProcessor/clearParameters)
    /// </summary>
    void ClearParameters();

    /// <summary>
    /// The `getParameter()` method of the XSLTProcessor interface returns the value of a parameter (`&lt;xsl:param&gt;`) from the stylesheet imported in the processor.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/XSLTProcessor/getParameter)
    /// </summary>
    object GetParameter(object namespaceURI, string localName);

    /// <summary>
    /// The `importStylesheet()` method of the XSLTProcessor interface imports an XSLT stylesheet for the processor.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/XSLTProcessor/importStylesheet)
    /// </summary>
    void ImportStylesheet(INode style);

    /// <summary>
    /// The `removeParameter()` method of the XSLTProcessor interface removes the parameter (`&lt;xsl:param&gt;`) and its value from the stylesheet imported in the processor.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/XSLTProcessor/removeParameter)
    /// </summary>
    void RemoveParameter(object namespaceURI, string localName);

    /// <summary>
    /// The `reset()` method of the XSLTProcessor interface removes all parameters (`&lt;xsl:param&gt;`) and the XSLT stylesheet from the processor.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/XSLTProcessor/reset)
    /// </summary>
    void Reset();

    /// <summary>
    /// The `setParameter()` method of the XSLTProcessor interface sets the value of a parameter (`&lt;xsl:param&gt;`) in the stylesheet imported in the processor.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/XSLTProcessor/setParameter)
    /// </summary>
    void SetParameter(object namespaceURI, string localName, object @value);

    /// <summary>
    /// The `transformToDocument()` method of the XSLTProcessor interface transforms the provided Node source to a Document using the XSLT stylesheet associated with `XSLTProcessor`.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/XSLTProcessor/transformToDocument)
    /// </summary>
    IDocument TransformToDocument(INode source);

    /// <summary>
    /// The `transformToFragment()` method of the XSLTProcessor interface transforms a provided Node source to a DocumentFragment using the XSLT stylesheet associated with the `XSLTProcessor`.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/XSLTProcessor/transformToFragment)
    /// </summary>
    IDocumentFragment TransformToFragment(INode source, IDocument output);
}
