#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The `AnimationTimeline` interface of the Web Animations API represents the timeline of an animation.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AnimationTimeline)
/// </summary>
public partial interface IAnimationTimeline : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`currentTime`** read-only property of the Web Animations API's AnimationTimeline interface returns the timeline's current time in milliseconds, or `null` if the timeline is inactive.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AnimationTimeline/currentTime)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("currentTime", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "CSSNumberish | null", Nullable = true, Streamable = false, StructuredClone = false, UnsupportedReason = "Union 'CSSNumberish | null' is unsupported: Union 'CSSNumberish' has incompatible transports: json-value, js-reference.")]
    global::System.Threading.Tasks.ValueTask<CSSNumberish?> GetCurrentTimeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CSSNumberish?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "currentTime", global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("CSSNumberish | null", "Union 'CSSNumberish | null' is unsupported: Union 'CSSNumberish' has incompatible transports: json-value, js-reference.", nullable: true), cancellationToken);
}


public sealed class AnimationTimelineDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IAnimationTimeline
{
}
