#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`AudioNode`** interface is a generic interface for representing an audio processing module.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioNode)
/// </summary>
public partial interface IAudioNode : IEventTarget, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`channelCount`** property of the AudioNode interface represents an integer used to determine how many channels are used when up-mixing and down-mixing connections to any inputs to the node.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioNode/channelCount)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("channelCount", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetChannelCountAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "channelCount", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("channelCount", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetChannelCountAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "channelCount", value, cancellationToken);

    /// <summary>
/// The `channelCountMode` property of the AudioNode interface represents an enumerated value describing the way channels must be matched between the node's inputs and outputs.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioNode/channelCountMode)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("channelCountMode", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "ChannelCountMode", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<ChannelCountMode> GetChannelCountModeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ChannelCountMode>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "channelCountMode", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("ChannelCountMode", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("channelCountMode", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "ChannelCountMode", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetChannelCountModeAsync(ChannelCountMode value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "channelCountMode", value, cancellationToken);

    /// <summary>
/// The **`channelInterpretation`** property of the AudioNode interface represents an enumerated value describing how input channels are mapped to output channels when the number of inputs/outputs is different.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioNode/channelInterpretation)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("channelInterpretation", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "ChannelInterpretation", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<ChannelInterpretation> GetChannelInterpretationAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ChannelInterpretation>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "channelInterpretation", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("ChannelInterpretation", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("channelInterpretation", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "ChannelInterpretation", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetChannelInterpretationAsync(ChannelInterpretation value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "channelInterpretation", value, cancellationToken);

    /// <summary>
/// The read-only `context` property of the the node is participating in.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioNode/context)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("context", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "BaseAudioContext", Nullable = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<IBaseAudioContext> GetContextAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<IBaseAudioContext>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "context", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("BaseAudioContext", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The `numberOfInputs` property of the AudioNode interface returns the number of inputs feeding the node.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioNode/numberOfInputs)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("numberOfInputs", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetNumberOfInputsAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "numberOfInputs", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);

    /// <summary>
/// The `numberOfOutputs` property of the AudioNode interface returns the number of outputs coming out of the node.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioNode/numberOfOutputs)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("numberOfOutputs", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetNumberOfOutputsAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "numberOfOutputs", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);

    /// <summary>
/// The `connect()` method of the AudioNode interface lets you connect one of the node's outputs to a target, which may be either another `AudioNode` (thereby directing the sound data to the specified node) or an change the value of that parameter over time.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioNode/connect)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:connect`0<>(AudioNode<>:optional=False:rest=False,NumberKeyword:optional=True:rest=False,NumberKeyword:optional=True:rest=False)[clr:IAudioNode,double,double]->IAudioNode@transport:js-reference:False:False:False:AudioNode", "connect", global::Microsoft.JSInterop.DomTransportKind.JsReference, "AudioNode", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<IAudioNode> ConnectAsync(IAudioNode destinationNode, double output = default, double input = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<IAudioNode>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "connect", [destinationNode, output, input], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("AudioNode", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:connect`0<>(AudioParam<>:optional=False:rest=False,NumberKeyword:optional=True:rest=False)[clr:IAudioParam,double]->void@transport:json-value:False:False:True:void", "connect", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask ConnectAsync(IAudioParam destinationParam, double output = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "connect", [destinationParam, output], cancellationToken);

    /// <summary>
/// The **`disconnect()`** method of the AudioNode interface lets you disconnect one or more nodes from the node on which the method is called.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/AudioNode/disconnect)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:disconnect`0<>()[clr:]->void@transport:json-value:False:False:True:void", "disconnect", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask DisconnectAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "disconnect", null, cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:disconnect`0<>(NumberKeyword:optional=False:rest=False)[clr:double]->void@transport:json-value:False:False:True:void", "disconnect", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask DisconnectAsync(double output, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "disconnect", [output], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:disconnect`0<>(AudioNode<>:optional=False:rest=False)[clr:IAudioNode]->void@transport:json-value:False:False:True:void", "disconnect", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask DisconnectAsync(IAudioNode destinationNode, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "disconnect", [destinationNode], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:disconnect`0<>(AudioNode<>:optional=False:rest=False,NumberKeyword:optional=False:rest=False)[clr:IAudioNode,double]->void@transport:json-value:False:False:True:void", "disconnect", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask DisconnectAsync(IAudioNode destinationNode, double output, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "disconnect", [destinationNode, output], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:disconnect`0<>(AudioNode<>:optional=False:rest=False,NumberKeyword:optional=False:rest=False,NumberKeyword:optional=False:rest=False)[clr:IAudioNode,double,double]->void@transport:json-value:False:False:True:void", "disconnect", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask DisconnectAsync(IAudioNode destinationNode, double output, double input, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "disconnect", [destinationNode, output, input], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:disconnect`0<>(AudioParam<>:optional=False:rest=False)[clr:IAudioParam]->void@transport:json-value:False:False:True:void", "disconnect", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask DisconnectAsync(IAudioParam destinationParam, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "disconnect", [destinationParam], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:disconnect`0<>(AudioParam<>:optional=False:rest=False,NumberKeyword:optional=False:rest=False)[clr:IAudioParam,double]->void@transport:json-value:False:False:True:void", "disconnect", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask DisconnectAsync(IAudioParam destinationParam, double output, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "disconnect", [destinationParam, output], cancellationToken);
}


public sealed class AudioNodeDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IAudioNode
{
}
