#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ICanvasTextDrawingStyles : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/direction)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("direction", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasDirection", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<CanvasDirection> GetDirectionAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CanvasDirection>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "direction", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("CanvasDirection", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("direction", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasDirection", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetDirectionAsync(CanvasDirection value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "direction", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/font)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("font", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetFontAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "font", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("font", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetFontAsync(string value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "font", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/fontKerning)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("fontKerning", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasFontKerning", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<CanvasFontKerning> GetFontKerningAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CanvasFontKerning>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "fontKerning", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("CanvasFontKerning", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("fontKerning", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasFontKerning", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetFontKerningAsync(CanvasFontKerning value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "fontKerning", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/fontStretch)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("fontStretch", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasFontStretch", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<CanvasFontStretch> GetFontStretchAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CanvasFontStretch>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "fontStretch", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("CanvasFontStretch", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("fontStretch", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasFontStretch", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetFontStretchAsync(CanvasFontStretch value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "fontStretch", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/fontVariantCaps)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("fontVariantCaps", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasFontVariantCaps", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<CanvasFontVariantCaps> GetFontVariantCapsAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CanvasFontVariantCaps>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "fontVariantCaps", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("CanvasFontVariantCaps", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("fontVariantCaps", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasFontVariantCaps", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetFontVariantCapsAsync(CanvasFontVariantCaps value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "fontVariantCaps", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/letterSpacing)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("letterSpacing", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetLetterSpacingAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "letterSpacing", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("letterSpacing", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetLetterSpacingAsync(string value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "letterSpacing", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/textAlign)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("textAlign", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasTextAlign", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<CanvasTextAlign> GetTextAlignAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CanvasTextAlign>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "textAlign", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("CanvasTextAlign", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("textAlign", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasTextAlign", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetTextAlignAsync(CanvasTextAlign value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "textAlign", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/textBaseline)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("textBaseline", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasTextBaseline", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<CanvasTextBaseline> GetTextBaselineAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CanvasTextBaseline>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "textBaseline", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("CanvasTextBaseline", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("textBaseline", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasTextBaseline", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetTextBaselineAsync(CanvasTextBaseline value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "textBaseline", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/textRendering)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("textRendering", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasTextRendering", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<CanvasTextRendering> GetTextRenderingAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CanvasTextRendering>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "textRendering", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("CanvasTextRendering", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("textRendering", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "CanvasTextRendering", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetTextRenderingAsync(CanvasTextRendering value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "textRendering", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/wordSpacing)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("wordSpacing", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetWordSpacingAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "wordSpacing", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("wordSpacing", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetWordSpacingAsync(string value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "wordSpacing", value, cancellationToken);
}


public sealed class CanvasTextDrawingStylesDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), ICanvasTextDrawingStyles
{
}
