#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ICanvasShadowStyles : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/shadowBlur)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("shadowBlur", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetShadowBlurAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "shadowBlur", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("shadowBlur", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetShadowBlurAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "shadowBlur", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/shadowColor)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("shadowColor", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetShadowColorAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "shadowColor", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("shadowColor", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetShadowColorAsync(string value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "shadowColor", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/shadowOffsetX)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("shadowOffsetX", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetShadowOffsetXAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "shadowOffsetX", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("shadowOffsetX", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetShadowOffsetXAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "shadowOffsetX", value, cancellationToken);

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/shadowOffsetY)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("shadowOffsetY", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetShadowOffsetYAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "shadowOffsetY", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("shadowOffsetY", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetShadowOffsetYAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "shadowOffsetY", value, cancellationToken);
}


public sealed class CanvasShadowStylesDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), ICanvasShadowStyles
{
}
