#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`CSSScale`** interface of the CSS Typed Object Model API represents the scale() and scale3d() values of the individual transform property in CSS.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSScale)
/// </summary>
public partial interface ICSSScale : ICSSTransformComponent, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`x`** property of the translating vector.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSScale/x)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("x", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "CSSNumberish", Nullable = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Union 'CSSNumberish' has incompatible transports: json-value, js-reference.")]
    global::System.Threading.Tasks.ValueTask<CSSNumberish> GetXAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CSSNumberish>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "x", global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("CSSNumberish", "Union 'CSSNumberish' has incompatible transports: json-value, js-reference.", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("x", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "CSSNumberish", Nullable = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Union 'CSSNumberish' has incompatible transports: json-value, js-reference.")]
    global::System.Threading.Tasks.ValueTask SetXAsync(CSSNumberish value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "x", value, cancellationToken);

    /// <summary>
/// The **`y`** property of the translating vector.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSScale/y)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("y", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "CSSNumberish", Nullable = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Union 'CSSNumberish' has incompatible transports: json-value, js-reference.")]
    global::System.Threading.Tasks.ValueTask<CSSNumberish> GetYAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CSSNumberish>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "y", global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("CSSNumberish", "Union 'CSSNumberish' has incompatible transports: json-value, js-reference.", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("y", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "CSSNumberish", Nullable = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Union 'CSSNumberish' has incompatible transports: json-value, js-reference.")]
    global::System.Threading.Tasks.ValueTask SetYAsync(CSSNumberish value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "y", value, cancellationToken);

    /// <summary>
/// The **`z`** property of the vector.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSScale/z)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("z", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "CSSNumberish", Nullable = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Union 'CSSNumberish' has incompatible transports: json-value, js-reference.")]
    global::System.Threading.Tasks.ValueTask<CSSNumberish> GetZAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<CSSNumberish>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "z", global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("CSSNumberish", "Union 'CSSNumberish' has incompatible transports: json-value, js-reference.", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("z", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "CSSNumberish", Nullable = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Union 'CSSNumberish' has incompatible transports: json-value, js-reference.")]
    global::System.Threading.Tasks.ValueTask SetZAsync(CSSNumberish value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "z", value, cancellationToken);
}


public sealed class CSSScaleDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), ICSSScale
{
}
