#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`CSSFontPaletteValuesRule`** interface represents an
/// </summary>
public partial interface ICSSFontPaletteValuesRule : ICSSRule, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The read-only **`basePalette`** property of the CSSFontPaletteValuesRule interface indicates the base palette associated with the rule.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontPaletteValuesRule/basePalette)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("basePalette", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetBasePaletteAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "basePalette", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);

    /// <summary>
/// The read-only **`fontFamily`** property of the CSSFontPaletteValuesRule interface lists the font families the rule can be applied to.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontPaletteValuesRule/fontFamily)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("fontFamily", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetFontFamilyAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "fontFamily", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);

    /// <summary>
/// The read-only **`name`** property of the CSSFontPaletteValuesRule interface represents the name identifying the associated
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("name", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetNameAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "name", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);

    /// <summary>
/// The read-only **`overrideColors`** property of the CSSFontPaletteValuesRule interface is a string containing a list of color index and color pair that are to be used instead.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSSFontPaletteValuesRule/overrideColors)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("overrideColors", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetOverrideColorsAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "overrideColors", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);
}


public sealed class CSSFontPaletteValuesRuleDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), ICSSFontPaletteValuesRule
{
}
