#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`EncodedVideoChunk`** interface of the WebCodecs API represents a chunk of encoded video data.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EncodedVideoChunk)
/// </summary>
public partial interface IEncodedVideoChunk : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`byteLength`** read-only property of the EncodedVideoChunk interface returns the length in bytes of the encoded video data.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EncodedVideoChunk/byteLength)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("byteLength", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetByteLengthAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "byteLength", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);

    /// <summary>
/// The **`duration`** read-only property of the EncodedVideoChunk interface returns an integer indicating the duration of the video in microseconds.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EncodedVideoChunk/duration)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("duration", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | null", Nullable = true, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double?> GetDurationAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "duration", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number | null", nullable: true), cancellationToken);

    /// <summary>
/// The **`timestamp`** read-only property of the EncodedVideoChunk interface returns an integer indicating the timestamp of the video in microseconds.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EncodedVideoChunk/timestamp)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("timestamp", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetTimestampAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "timestamp", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);

    /// <summary>
/// The **`type`** read-only property of the EncodedVideoChunk interface returns a value indicating whether the video chunk is a key chunk, which does not rely on other frames for decoding.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EncodedVideoChunk/type)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("type", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "EncodedVideoChunkType", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<EncodedVideoChunkType> GetTypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<EncodedVideoChunkType>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "type", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("EncodedVideoChunkType", nullable: false), cancellationToken);

    /// <summary>
/// The **`copyTo()`** method of the EncodedVideoChunk interface copies the encoded chunk of video data.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EncodedVideoChunk/copyTo)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:copyTo`0<>(AllowSharedBufferSource<>:optional=False:rest=False)[clr:AllowSharedBufferSource]->void@transport:json-value:False:False:True:void", "copyTo", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask CopyToAsync(AllowSharedBufferSource destination, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "copyTo", [destination], cancellationToken);
}


public sealed class EncodedVideoChunkDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IEncodedVideoChunk
{
}
