#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`FormData`** interface provides a way to construct a set of key/value pairs representing form fields and their values, which can be sent using the Window/fetch, XMLHttpRequest.send() or navigator.sendBeacon() methods.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FormData)
/// </summary>
public partial interface IFormData : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`append()`** method of the FormData interface appends a new value onto an existing key inside a `FormData` object, or adds the key if it does not already exist.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FormData/append)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:append`0<>(StringKeyword:optional=False:rest=False,union(StringKeyword|Blob<>):optional=False:rest=False)[clr:string,global::Blazor.DOM.AdvancedTypes.ClipboardItemDataUnionShape_14acc04c76]->void@transport:json-value:False:False:True:void", "append", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask AppendAsync(string name, global::Blazor.DOM.AdvancedTypes.ClipboardItemDataUnionShape_14acc04c76 @value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "append", [name, @value], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:append`0<>(StringKeyword:optional=False:rest=False,StringKeyword:optional=False:rest=False)[clr:string,string]->void@transport:json-value:False:False:True:void", "append", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask AppendAsync(string name, string @value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "append", [name, @value], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:append`0<>(StringKeyword:optional=False:rest=False,Blob<>:optional=False:rest=False,StringKeyword:optional=True:rest=False)[clr:string,IBlob,string]->void@transport:json-value:False:False:True:void", "append", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask AppendAsync(string name, IBlob blobValue, string? filename = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "append", [name, blobValue, filename], cancellationToken);

    /// <summary>
/// The **`delete()`** method of the FormData interface deletes a key and its value(s) from a `FormData` object.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FormData/delete)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:delete`0<>(StringKeyword:optional=False:rest=False)[clr:string]->void@transport:json-value:False:False:True:void", "delete", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask DeleteAsync(string name, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "delete", [name], cancellationToken);

    /// <summary>
/// The **`get()`** method of the FormData interface returns the first value associated with a given key from within a `FormData` object.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FormData/get)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:get`0<>(StringKeyword:optional=False:rest=False)[clr:string]->FormDataEntryValue?@transport:unsupported:True:False:False:FormDataEntryValue | null", "get", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "FormDataEntryValue | null", Nullable = true, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Union 'FormDataEntryValue | null' is unsupported: Union 'FormDataEntryValue' has incompatible transports: js-reference, json-value.")]
    global::System.Threading.Tasks.ValueTask<FormDataEntryValue?> GetAsync(string name, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<FormDataEntryValue?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "get", [name], global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("FormDataEntryValue | null", "Union 'FormDataEntryValue | null' is unsupported: Union 'FormDataEntryValue' has incompatible transports: js-reference, json-value.", nullable: true), cancellationToken);

    /// <summary>
/// The **`getAll()`** method of the FormData interface returns all the values associated with a given key from within a `FormData` object.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FormData/getAll)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:getAll`0<>(StringKeyword:optional=False:rest=False)[clr:string]->global::Microsoft.JSInterop.IBrowserArray<FormDataEntryValue>@transport:js-reference:False:False:False:FormDataEntryValue[]", "getAll", global::Microsoft.JSInterop.DomTransportKind.JsReference, "FormDataEntryValue[]", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<global::Microsoft.JSInterop.IBrowserArray<FormDataEntryValue>> GetAllAsync(string name, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<global::Microsoft.JSInterop.IBrowserArray<FormDataEntryValue>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "getAll", [name], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("FormDataEntryValue[]", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The **`has()`** method of the FormData interface returns whether a `FormData` object contains a certain key.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FormData/has)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:has`0<>(StringKeyword:optional=False:rest=False)[clr:string]->bool@transport:json-value:False:False:True:boolean", "has", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<bool> HasAsync(string name, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<bool>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "has", [name], global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("boolean", nullable: false), cancellationToken);

    /// <summary>
/// The **`set()`** method of the FormData interface sets a new value for an existing key inside a `FormData` object, or adds the key/value if it does not already exist.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FormData/set)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:set`0<>(StringKeyword:optional=False:rest=False,union(StringKeyword|Blob<>):optional=False:rest=False)[clr:string,global::Blazor.DOM.AdvancedTypes.ClipboardItemDataUnionShape_14acc04c76]->void@transport:json-value:False:False:True:void", "set", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetAsync(string name, global::Blazor.DOM.AdvancedTypes.ClipboardItemDataUnionShape_14acc04c76 @value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "set", [name, @value], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:set`0<>(StringKeyword:optional=False:rest=False,StringKeyword:optional=False:rest=False)[clr:string,string]->void@transport:json-value:False:False:True:void", "set", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetAsync(string name, string @value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "set", [name, @value], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:set`0<>(StringKeyword:optional=False:rest=False,Blob<>:optional=False:rest=False,StringKeyword:optional=True:rest=False)[clr:string,IBlob,string]->void@transport:json-value:False:False:True:void", "set", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetAsync(string name, IBlob blobValue, string? filename = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "set", [name, blobValue, filename], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:forEach`0<>(function:(value: FormDataEntryValue, key: string, parent: FormData) => void:optional=False:rest=False,AnyKeyword:optional=True:rest=False)[clr:Action<FormDataEntryValue, string, IFormData>,object]->void@transport:json-value:False:False:True:void", "forEach", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask ForEachAsync(Action<FormDataEntryValue, string, IFormData> callbackfn, object? thisArg = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "forEach", [callbackfn, thisArg], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:Symbol.iterator`0<>()[clr:]->IFormDataIterator<global::Blazor.DOM.AdvancedTypes.FormDataReferenceTupleShape_06d9cb3b1c>@transport:unsupported:False:False:False:FormDataIterator<[string, FormDataEntryValue]>", "Symbol.iterator", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "FormDataIterator<[string, FormDataEntryValue]>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.")]
[global::Microsoft.JSInterop.DomSymbol(global::Microsoft.JSInterop.DomWellKnownSymbol.Iterator)]
    global::System.Threading.Tasks.ValueTask<IFormDataIterator<global::Blazor.DOM.AdvancedTypes.FormDataReferenceTupleShape_06d9cb3b1c>> SymbolIteratorAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<IFormDataIterator<global::Blazor.DOM.AdvancedTypes.FormDataReferenceTupleShape_06d9cb3b1c>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "Symbol.iterator", null, global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("FormDataIterator<[string, FormDataEntryValue]>", "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.", nullable: false), cancellationToken);

    /// <summary>
/// Returns an array of key, value pairs for every entry in the list.
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:entries`0<>()[clr:]->IFormDataIterator<global::Blazor.DOM.AdvancedTypes.FormDataReferenceTupleShape_4eacfd5e90>@transport:unsupported:False:False:False:FormDataIterator<[string, FormDataEntryValue]>", "entries", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "FormDataIterator<[string, FormDataEntryValue]>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.")]
    global::System.Threading.Tasks.ValueTask<IFormDataIterator<global::Blazor.DOM.AdvancedTypes.FormDataReferenceTupleShape_4eacfd5e90>> EntriesAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<IFormDataIterator<global::Blazor.DOM.AdvancedTypes.FormDataReferenceTupleShape_4eacfd5e90>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "entries", null, global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("FormDataIterator<[string, FormDataEntryValue]>", "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.", nullable: false), cancellationToken);

    /// <summary>
/// Returns a list of keys in the list.
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:keys`0<>()[clr:]->IFormDataIterator<string>@transport:unsupported:False:False:False:FormDataIterator<string>", "keys", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "FormDataIterator<string>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.")]
    global::System.Threading.Tasks.ValueTask<IFormDataIterator<string>> KeysAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<IFormDataIterator<string>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "keys", null, global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("FormDataIterator<string>", "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.", nullable: false), cancellationToken);

    /// <summary>
/// Returns a list of values in the list.
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:values`0<>()[clr:]->IFormDataIterator<FormDataEntryValue>@transport:unsupported:False:False:False:FormDataIterator<FormDataEntryValue>", "values", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "FormDataIterator<FormDataEntryValue>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.")]
    global::System.Threading.Tasks.ValueTask<IFormDataIterator<FormDataEntryValue>> ValuesAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<IFormDataIterator<FormDataEntryValue>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "values", null, global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("FormDataIterator<FormDataEntryValue>", "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.", nullable: false), cancellationToken);
}


public sealed class FormDataDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IFormData
{
}
