#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`HTMLMarqueeElement`** interface provides methods to manipulate marquee elements.
/// </summary>
[Obsolete]
[global::Microsoft.JSInterop.DomEventTarget("HTMLMarqueeElement", "HTMLElementEventMap")]
public partial interface IHTMLMarqueeElement : IHTMLElement, global::Microsoft.JSInterop.IDomDispatchProxy
{
    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("behavior", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetBehaviorAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "behavior", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("behavior", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetBehaviorAsync(string value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "behavior", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("bgColor", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetBgColorAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "bgColor", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("bgColor", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetBgColorAsync(string value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "bgColor", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("direction", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetDirectionAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "direction", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("direction", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetDirectionAsync(string value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "direction", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("height", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetHeightAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "height", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("height", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetHeightAsync(string value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "height", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("hspace", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetHspaceAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "hspace", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("hspace", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetHspaceAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "hspace", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("loop", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetLoopAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "loop", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("loop", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetLoopAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "loop", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("scrollAmount", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetScrollAmountAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "scrollAmount", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("scrollAmount", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetScrollAmountAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "scrollAmount", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("scrollDelay", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetScrollDelayAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "scrollDelay", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("scrollDelay", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetScrollDelayAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "scrollDelay", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("trueSpeed", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<bool> GetTrueSpeedAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<bool>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "trueSpeed", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("boolean", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("trueSpeed", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetTrueSpeedAsync(bool value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "trueSpeed", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("vspace", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetVspaceAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "vspace", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("vspace", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetVspaceAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "vspace", value, cancellationToken);

    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("width", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<string> GetWidthAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "width", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false), cancellationToken);


    [Obsolete]
    [global::Microsoft.JSInterop.DomAccessor("width", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetWidthAsync(string value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "width", value, cancellationToken);

    [Obsolete]
[global::Microsoft.JSInterop.DomOperation("js:start`0<>()[clr:]->void@transport:json-value:False:False:True:void", "start", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask StartAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "start", null, cancellationToken);

    [Obsolete]
[global::Microsoft.JSInterop.DomOperation("js:stop`0<>()[clr:]->void@transport:json-value:False:False:True:void", "stop", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask StopAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "stop", null, cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask AddEventListenerAsync(string type, EventListenerOrEventListenerObject listener, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask AddEventListenerAsync(string type, EventListenerOrEventListenerObject listener, bool capture, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, capture], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,AddEventListenerOptions]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask AddEventListenerAsync(string type, EventListenerOrEventListenerObject listener, AddEventListenerOptions? options, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, options], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask RemoveEventListenerAsync(string type, EventListenerOrEventListenerObject listener, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask RemoveEventListenerAsync(string type, EventListenerOrEventListenerObject listener, bool capture, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, capture], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,EventListenerOptions]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask RemoveEventListenerAsync(string type, EventListenerOrEventListenerObject listener, EventListenerOptions? options, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, options], cancellationToken);
}


public sealed class HTMLMarqueeElementDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IHTMLMarqueeElement
{
}
