#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`NavigationActivation`** interface of the Navigation API represents a recent cross-document navigation.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigationActivation)
/// </summary>
public partial interface INavigationActivation : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`entry`** read-only property of the NavigationActivation interface contains a NavigationHistoryEntry object representing the history entry for the inbound ('to') document in the navigation.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigationActivation/entry)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("entry", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "NavigationHistoryEntry", Nullable = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<INavigationHistoryEntry> GetEntryAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<INavigationHistoryEntry>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "entry", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("NavigationHistoryEntry", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The **`from`** read-only property of the NavigationActivation interface contains a NavigationHistoryEntry object representing the history entry for the outgoing ('from') document in the navigation.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigationActivation/from)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("from", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "NavigationHistoryEntry | null", Nullable = true, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<INavigationHistoryEntry?> GetFromAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<INavigationHistoryEntry?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "from", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("NavigationHistoryEntry | null", nullable: true, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The **`navigationType`** read-only property of the NavigationActivation interface contains a string indicating the type of navigation.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/NavigationActivation/navigationType)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("navigationType", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "NavigationType", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<NavigationType> GetNavigationTypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<NavigationType>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "navigationType", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("NavigationType", nullable: false), cancellationToken);
}


public sealed class NavigationActivationDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), INavigationActivation
{
}
