#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// **`PerformanceMeasure`** is an _abstract_ interface for PerformanceEntry objects with an PerformanceEntry.entryType of `'measure'`.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceMeasure)
/// </summary>
public partial interface IPerformanceMeasure : IPerformanceEntry, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The read-only **`detail`** property returns arbitrary metadata that was included in the mark upon construction (when using Performance.measure.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PerformanceMeasure/detail)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("detail", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "any", Nullable = false, Streamable = false, StructuredClone = false, UnsupportedReason = "TypeScript 'any' requires an explicit runtime transport escape hatch.")]
    global::System.Threading.Tasks.ValueTask<object> GetDetailAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<object>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "detail", global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("any", "TypeScript 'any' requires an explicit runtime transport escape hatch.", nullable: false), cancellationToken);
}


public sealed class PerformanceMeasureDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IPerformanceMeasure
{
}
