#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`RTCError`** interface describes an error which has occurred while handling WebRTC operations.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCError)
/// </summary>
public partial interface IRTCError : IDOMException, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The RTCError interface's read-only **`errorDetail`** property is a string indicating the WebRTC-specific error code that occurred.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCError/errorDetail)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("errorDetail", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "RTCErrorDetailType", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<RTCErrorDetailType> GetErrorDetailAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<RTCErrorDetailType>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "errorDetail", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("RTCErrorDetailType", nullable: false), cancellationToken);

    /// <summary>
/// The RTCError read-only property **`receivedAlert`** specifies the fatal DTLS error which resulted in an alert being received from the remote peer.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCError/receivedAlert)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("receivedAlert", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | null", Nullable = true, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double?> GetReceivedAlertAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "receivedAlert", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number | null", nullable: true), cancellationToken);

    /// <summary>
/// The read-only **`sctpCauseCode`** property in an why the SCTP negotiation failed, if the `RTCError` represents an SCTP error.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCError/sctpCauseCode)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("sctpCauseCode", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | null", Nullable = true, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double?> GetSctpCauseCodeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "sctpCauseCode", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number | null", nullable: true), cancellationToken);

    /// <summary>
/// The RTCError interface's read-only property **`sdpLineNumber`** specifies the line number within the An unsigned integer value indicating the line within the SDP at which the syntax error described by the `RTCError` object occurred.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCError/sdpLineNumber)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("sdpLineNumber", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | null", Nullable = true, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double?> GetSdpLineNumberAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "sdpLineNumber", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number | null", nullable: true), cancellationToken);

    /// <summary>
/// The read-only **`sentAlert`** property in an while sending data to the remote peer, if the error represents an outbound DTLS error.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/RTCError/sentAlert)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("sentAlert", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | null", Nullable = true, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double?> GetSentAlertAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "sentAlert", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number | null", nullable: true), cancellationToken);
}


public sealed class RTCErrorDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IRTCError
{
}
