#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SVGFETurbulenceElement`** interface corresponds to the feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement)
/// </summary>
[global::Microsoft.JSInterop.DomEventTarget("SVGFETurbulenceElement", "SVGElementEventMap")]
public partial interface ISVGFETurbulenceElement : ISVGElement, ISVGFilterPrimitiveStandardAttributes, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`baseFrequencyX`** read-only property of the SVGFETurbulenceElement interface reflects the X component of the baseFrequency attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/baseFrequencyX)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("baseFrequencyX", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedNumber", Nullable = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<ISVGAnimatedNumber> GetBaseFrequencyXAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ISVGAnimatedNumber>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "baseFrequencyX", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedNumber", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The **`baseFrequencyY`** read-only property of the SVGFETurbulenceElement interface reflects the Y component of the baseFrequency attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/baseFrequencyY)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("baseFrequencyY", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedNumber", Nullable = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<ISVGAnimatedNumber> GetBaseFrequencyYAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ISVGAnimatedNumber>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "baseFrequencyY", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedNumber", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The **`numOctaves`** read-only property of the SVGFETurbulenceElement interface reflects the numOctaves attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/numOctaves)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("numOctaves", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedInteger", Nullable = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<ISVGAnimatedInteger> GetNumOctavesAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ISVGAnimatedInteger>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "numOctaves", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedInteger", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The **`seed`** read-only property of the SVGFETurbulenceElement interface reflects the seed attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/seed)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("seed", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedNumber", Nullable = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<ISVGAnimatedNumber> GetSeedAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ISVGAnimatedNumber>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "seed", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedNumber", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The **`stitchTiles`** read-only property of the SVGFETurbulenceElement interface reflects the stitchTiles attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/stitchTiles)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("stitchTiles", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedEnumeration", Nullable = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<ISVGAnimatedEnumeration> GetStitchTilesAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ISVGAnimatedEnumeration>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "stitchTiles", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedEnumeration", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The **`type`** read-only property of the SVGFETurbulenceElement interface reflects the type attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/type)
/// </summary>
    [global::Microsoft.JSInterop.DomAccessor("type", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedEnumeration", Nullable = false, Streamable = false, StructuredClone = false)]
    global::System.Threading.Tasks.ValueTask<ISVGAnimatedEnumeration> GetTypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ISVGAnimatedEnumeration>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "type", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedEnumeration", nullable: false, streamable: false, structuredClone: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("SVG_TURBULENCE_TYPE_UNKNOWN", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "0", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetSVGTURBULENCETYPEUNKNOWNAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_TURBULENCE_TYPE_UNKNOWN", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("0", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("SVG_TURBULENCE_TYPE_FRACTALNOISE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "1", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetSVGTURBULENCETYPEFRACTALNOISEAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_TURBULENCE_TYPE_FRACTALNOISE", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("1", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("SVG_TURBULENCE_TYPE_TURBULENCE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "2", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetSVGTURBULENCETYPETURBULENCEAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_TURBULENCE_TYPE_TURBULENCE", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("2", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("SVG_STITCHTYPE_UNKNOWN", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "0", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetSVGSTITCHTYPEUNKNOWNAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_STITCHTYPE_UNKNOWN", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("0", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("SVG_STITCHTYPE_STITCH", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "1", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetSVGSTITCHTYPESTITCHAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_STITCHTYPE_STITCH", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("1", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("SVG_STITCHTYPE_NOSTITCH", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "2", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetSVGSTITCHTYPENOSTITCHAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_STITCHTYPE_NOSTITCH", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("2", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask AddEventListenerAsync(string type, EventListenerOrEventListenerObject listener, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask AddEventListenerAsync(string type, EventListenerOrEventListenerObject listener, bool capture, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, capture], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,AddEventListenerOptions]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask AddEventListenerAsync(string type, EventListenerOrEventListenerObject listener, AddEventListenerOptions? options, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, options], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask RemoveEventListenerAsync(string type, EventListenerOrEventListenerObject listener, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask RemoveEventListenerAsync(string type, EventListenerOrEventListenerObject listener, bool capture, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, capture], cancellationToken);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,EventListenerOptions]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask RemoveEventListenerAsync(string type, EventListenerOrEventListenerObject listener, EventListenerOptions? options, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, options], cancellationToken);
}


public sealed class SVGFETurbulenceElementDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), ISVGFETurbulenceElement
{
}
