#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`TextDecoderStream`** interface of the Encoding API converts a stream of text in a binary encoding, such as UTF-8 etc., to a stream of strings.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/TextDecoderStream)
/// </summary>
public partial interface ITextDecoderStream : IGenericTransformStream, ITextDecoderCommon, global::Microsoft.JSInterop.IDomDispatchProxy
{
    [global::Microsoft.JSInterop.DomAccessor("readable", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Transferable, "ReadableStream<string>", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<IReadableStream<string>> GetReadableAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<IReadableStream<string>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "readable", global::Microsoft.JSInterop.DomTransportDescriptor.Transferable("ReadableStream<string>", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("writable", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Transferable, "WritableStream<BufferSource>", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<IWritableStream<BufferSource>> GetWritableAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<IWritableStream<BufferSource>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "writable", global::Microsoft.JSInterop.DomTransportDescriptor.Transferable("WritableStream<BufferSource>", nullable: false), cancellationToken);
}


public sealed class TextDecoderStreamDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), ITextDecoderStream
{
}
