#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IMediaRecorderFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    global::System.Threading.Tasks.ValueTask<IMediaRecorder> GetPrototypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<IMediaRecorder>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IMediaRecorder>("prototype"), cancellationToken);
    global::System.Threading.Tasks.ValueTask SetPrototypeAsync(IMediaRecorder value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value, cancellationToken);

    global::System.Threading.Tasks.ValueTask<IMediaRecorder> CreateAsync(IMediaStream stream, MediaRecorderOptions? options = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.ConstructAsync<IMediaRecorder>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "MediaRecorder", [stream, options], cancellationToken);

    /// <summary>
    /// The **`isTypeSupported()`** static method of the MediaRecorder interface returns a Boolean which is `true` if the MIME media type specified is one the user agent should be able to successfully record.
    ///
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaRecorder/isTypeSupported_static)
    /// </summary>
    global::System.Threading.Tasks.ValueTask<bool> IsTypeSupportedAsync(string type, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<bool>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "isTypeSupported", [type], global::Microsoft.JSInterop.DomDispatch.InferTransport<bool>("isTypeSupported"), cancellationToken);
}


public sealed class MediaRecorderFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IMediaRecorderFactory
{
}
