#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IMediaQueryListEventFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    global::System.Threading.Tasks.ValueTask<IMediaQueryListEvent> GetPrototypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<IMediaQueryListEvent>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IMediaQueryListEvent>("prototype"), cancellationToken);
    global::System.Threading.Tasks.ValueTask SetPrototypeAsync(IMediaQueryListEvent value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value, cancellationToken);

    global::System.Threading.Tasks.ValueTask<IMediaQueryListEvent> CreateAsync(string type, MediaQueryListEventInit? eventInitDict = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.ConstructAsync<IMediaQueryListEvent>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "MediaQueryListEvent", [type, eventInitDict], cancellationToken);
}


public sealed class MediaQueryListEventFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IMediaQueryListEventFactory
{
}
