#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IRTCIceCandidateFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    global::System.Threading.Tasks.ValueTask<IRTCIceCandidate> GetPrototypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<IRTCIceCandidate>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IRTCIceCandidate>("prototype"), cancellationToken);
    global::System.Threading.Tasks.ValueTask SetPrototypeAsync(IRTCIceCandidate value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value, cancellationToken);

    global::System.Threading.Tasks.ValueTask<IRTCIceCandidate> CreateAsync(RTCLocalIceCandidateInit? candidateInitDict = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.ConstructAsync<IRTCIceCandidate>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "RTCIceCandidate", [candidateInitDict], cancellationToken);
}


public sealed class RTCIceCandidateFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IRTCIceCandidateFactory
{
}
