#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ISVGAngleFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    global::System.Threading.Tasks.ValueTask<ISVGAngle> GetPrototypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ISVGAngle>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<ISVGAngle>("prototype"), cancellationToken);
    global::System.Threading.Tasks.ValueTask SetPrototypeAsync(ISVGAngle value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value, cancellationToken);

    global::System.Threading.Tasks.ValueTask<ISVGAngle> CreateAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.ConstructAsync<ISVGAngle>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVGAngle", null, cancellationToken);

    global::System.Threading.Tasks.ValueTask<double> GetSVGANGLETYPEUNKNOWNAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_ANGLETYPE_UNKNOWN", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("SVG_ANGLETYPE_UNKNOWN"), cancellationToken);

    global::System.Threading.Tasks.ValueTask<double> GetSVGANGLETYPEUNSPECIFIEDAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_ANGLETYPE_UNSPECIFIED", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("SVG_ANGLETYPE_UNSPECIFIED"), cancellationToken);

    global::System.Threading.Tasks.ValueTask<double> GetSVGANGLETYPEDEGAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_ANGLETYPE_DEG", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("SVG_ANGLETYPE_DEG"), cancellationToken);

    global::System.Threading.Tasks.ValueTask<double> GetSVGANGLETYPERADAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_ANGLETYPE_RAD", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("SVG_ANGLETYPE_RAD"), cancellationToken);

    global::System.Threading.Tasks.ValueTask<double> GetSVGANGLETYPEGRADAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_ANGLETYPE_GRAD", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("SVG_ANGLETYPE_GRAD"), cancellationToken);
}


public sealed class SVGAngleFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), ISVGAngleFactory
{
}
