#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ITransformStreamFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    global::System.Threading.Tasks.ValueTask<ITransformStream<object, object>> GetPrototypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<ITransformStream<object, object>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<ITransformStream<object, object>>("prototype"), cancellationToken);
    global::System.Threading.Tasks.ValueTask SetPrototypeAsync(ITransformStream<object, object> value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value, cancellationToken);

    global::System.Threading.Tasks.ValueTask<ITransformStream<object, object>> CreateAsync(Transformer<object, object>? transformer = default, QueuingStrategy<object>? writableStrategy = default, QueuingStrategy<object>? readableStrategy = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.ConstructAsync<ITransformStream<object, object>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "TransformStream", [transformer, writableStrategy, readableStrategy], cancellationToken);

    global::System.Threading.Tasks.ValueTask<ITransformStream<I, object>> CreateAsync<I>(Transformer<I, object>? transformer = default, QueuingStrategy<I>? writableStrategy = default, QueuingStrategy<object>? readableStrategy = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.ConstructAsync<ITransformStream<I, object>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "TransformStream", [transformer, writableStrategy, readableStrategy], cancellationToken);

    // TypeScript generic default: I = object.
    // TypeScript generic default: O = object.
    global::System.Threading.Tasks.ValueTask<ITransformStream<I, O>> CreateAsync<I, O>(Transformer<I, O>? transformer = default, QueuingStrategy<I>? writableStrategy = default, QueuingStrategy<O>? readableStrategy = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.ConstructAsync<ITransformStream<I, O>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "TransformStream", [transformer, writableStrategy, readableStrategy], cancellationToken);
}


public sealed class TransformStreamFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), ITransformStreamFactory
{
}
