#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IWebTransportErrorFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    global::System.Threading.Tasks.ValueTask<IWebTransportError> GetPrototypeAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<IWebTransportError>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IWebTransportError>("prototype"), cancellationToken);
    global::System.Threading.Tasks.ValueTask SetPrototypeAsync(IWebTransportError value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value, cancellationToken);

    global::System.Threading.Tasks.ValueTask<IWebTransportError> CreateAsync(string? message = default, WebTransportErrorOptions? options = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.ConstructAsync<IWebTransportError>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "WebTransportError", [message, options], cancellationToken);
}


public sealed class WebTransportErrorFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), IWebTransportErrorFactory
{
}
