#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

// Requires secure context (HTTPS).
public partial interface IBluetoothManufacturerDataMap : global::Microsoft.JSInterop.IDomProxy
{
    [global::Microsoft.JSInterop.DomAccessor("size", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
double Size { get; }

    global::Microsoft.JSInterop.IBrowserIterableIterator<global::Blazor.DOM.AdvancedTypes.BluetoothManufacturerDataMapReferenceTupleShape_6df343f0f0> Entries();

    void ForEach(Action<System.Memory<byte>, double, IBluetoothManufacturerDataMap> callbackfn, object? thisArg = default);

    global::Blazor.DOM.AdvancedTypes.BluetoothManufacturerDataMapUnionShape_ad421b3e15 Get(double key);

    bool Has(double key);

    global::Microsoft.JSInterop.IBrowserIterableIterator<double> Keys();

    global::Microsoft.JSInterop.IBrowserIterableIterator<System.Memory<byte>> Values();

    [global::Microsoft.JSInterop.DomSymbol(global::Microsoft.JSInterop.DomWellKnownSymbol.Iterator)]
global::Microsoft.JSInterop.IBrowserIterableIterator<global::Blazor.DOM.AdvancedTypes.BluetoothManufacturerDataMapReferenceTupleShape_4b79dcecec> SymbolIterator();
}
