#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

// Requires secure context (HTTPS).
[global::Microsoft.JSInterop.DomEventTarget("GPUDevice", "__GPUDeviceEventMap")]
public partial interface IGPUDevice : IEventTarget, IGPUObjectBase, global::Microsoft.JSInterop.IDomEventTargetProxy
{
    /// <summary>
/// A set containing the {@link GPUFeatureName} values of the features
/// supported by the device (i.e. the ones with which it was created).
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("features", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "GPUSupportedFeatures", Nullable = false, Streamable = false, StructuredClone = false)]
GPUSupportedFeatures Features { get; }

    /// <summary>
/// Exposes the limits supported by the device
/// (which are exactly the ones with which it was created).
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("limits", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "GPUSupportedLimits", Nullable = false, Streamable = false, StructuredClone = false)]
IGPUSupportedLimits Limits { get; }

    /// <summary>
/// The primary {@link GPUQueue} for this device.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("queue", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "GPUQueue", Nullable = false, Streamable = false, StructuredClone = false)]
IGPUQueue Queue { get; }

    /// <summary>
/// A slot-backed attribute holding a promise which is created with the device, remains
/// pending for the lifetime of the device, then resolves when the device is lost.
/// Upon initialization, it is set to a new promise.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("lost", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "Promise<GPUDeviceLostInfo>", Nullable = false, Streamable = false, StructuredClone = false)]
global::Microsoft.JSInterop.IBrowserPromise<IGPUDeviceLostInfo> Lost { get; }

    /// <summary>
/// An event handler IDL attribute for the `uncapturederror` event type.
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("onuncapturederror", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "((this: GPUDevice, ev: GPUUncapturedErrorEvent) => any) | null", Nullable = true, Streamable = false, StructuredClone = false, UnsupportedReason = "Union '((this: GPUDevice, ev: GPUUncapturedErrorEvent) => any) | null' is unsupported: TypeScript '(this: GPUDevice, ev: GPUUncapturedErrorEvent) => any' has an ambiguous function shape.")]
[global::Microsoft.JSInterop.DomAccessor("onuncapturederror", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "((this: GPUDevice, ev: GPUUncapturedErrorEvent) => any) | null", Nullable = true, Streamable = false, StructuredClone = false, UnsupportedReason = "Union '((this: GPUDevice, ev: GPUUncapturedErrorEvent) => any) | null' is unsupported: TypeScript '(this: GPUDevice, ev: GPUUncapturedErrorEvent) => any' has an ambiguous function shape.")]
Func<IGPUUncapturedErrorEvent, object>? Onuncapturederror { get; set; }

    void AddEventListener(string type, EventListenerOrEventListenerObject listener);

    void AddEventListener(string type, EventListenerOrEventListenerObject listener, bool capture);

    void AddEventListener(string type, EventListenerOrEventListenerObject listener, AddEventListenerOptions? options);

    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener);

    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, bool capture);

    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, EventListenerOptions? options);

    /// <summary>
/// Creates a {@link GPUBuffer}.
/// </summary>
IGPUBuffer CreateBuffer(GPUBufferDescriptor descriptor);

    /// <summary>
/// Pops a GPU error scope off the {@link GPUDevice}.`[[errorScopeStack]]` for `this`
/// and resolves to **any** {@link GPUError} observed by the error scope, or `null` if none.
/// There is no guarantee of the ordering of promise resolution.
/// </summary>
[global::Microsoft.JSInterop.DomJavaScriptName("popErrorScope")]
ValueTask<IGPUError?> PopErrorScopeAsync();
}
