#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

// TypeScript generic default: R = object.
public partial interface IUnderlyingDefaultSource<R> : global::Microsoft.JSInterop.IDomProxy
{
}
