// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`DOMRectReadOnly`** interface specifies the standard properties (also used by DOMRect) to define a rectangle whose properties are immutable.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly)
/// </summary>
public partial interface IDOMRectReadOnly
{
    /// <summary>
    /// The **`bottom`** read-only property of the **`DOMRectReadOnly`** interface returns the bottom coordinate value of the `DOMRect`.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly/bottom)
    /// </summary>
    double Bottom { get; }
    /// <summary>
    /// The **`height`** read-only property of the **`DOMRectReadOnly`** interface represents the height of the `DOMRect`.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly/height)
    /// </summary>
    double Height { get; }
    /// <summary>
    /// The **`left`** read-only property of the **`DOMRectReadOnly`** interface returns the left coordinate value of the `DOMRect`.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly/left)
    /// </summary>
    double Left { get; }
    /// <summary>
    /// The **`right`** read-only property of the **`DOMRectReadOnly`** interface returns the right coordinate value of the `DOMRect`.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly/right)
    /// </summary>
    double Right { get; }
    /// <summary>
    /// The **`top`** read-only property of the **`DOMRectReadOnly`** interface returns the top coordinate value of the `DOMRect`.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly/top)
    /// </summary>
    double Top { get; }
    /// <summary>
    /// The **`width`** read-only property of the **`DOMRectReadOnly`** interface represents the width of the `DOMRect`.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly/width)
    /// </summary>
    double Width { get; }
    /// <summary>
    /// The **`x`** read-only property of the **`DOMRectReadOnly`** interface represents the x coordinate of the `DOMRect`'s origin.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly/x)
    /// </summary>
    double X { get; }
    /// <summary>
    /// The **`y`** read-only property of the **`DOMRectReadOnly`** interface represents the y coordinate of the `DOMRect`'s origin.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly/y)
    /// </summary>
    double Y { get; }

    /// <summary>
    /// The DOMRectReadOnly method `toJSON()` returns a JSON representation of the `DOMRectReadOnly` object.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMRectReadOnly/toJSON)
    /// </summary>
    object ToJSON();
}
