// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The `EXT_texture_compression_rgtc` extension is part of the WebGL API and exposes 4 RGTC compressed texture formats.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/EXT_texture_compression_rgtc)
/// </summary>
public partial interface IEXT_texture_compression_rgtc
{
    double COMPRESSEDREDRGTC1EXT { get; }
    double COMPRESSEDSIGNEDREDRGTC1EXT { get; }
    double COMPRESSEDREDGREENRGTC2EXT { get; }
    double COMPRESSEDSIGNEDREDGREENRGTC2EXT { get; }
}
