// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`FontFaceSet`** interface of the CSS Font Loading API manages the loading of font-faces and querying of their download status.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontFaceSet)
/// </summary>
public partial interface IFontFaceSet : IEventTarget
{
    // PROJECTION-FAILED: onloading — Unsupported union type 'parenthesized | null' at 'FontFaceSet.onloading'. Mixed unions (non-nullable, non-all-string-lit
    // PROJECTION-FAILED: onloadingdone — Unsupported union type 'parenthesized | null' at 'FontFaceSet.onloadingdone'. Mixed unions (non-nullable, non-all-string
    // PROJECTION-FAILED: onloadingerror — Unsupported union type 'parenthesized | null' at 'FontFaceSet.onloadingerror'. Mixed unions (non-nullable, non-all-strin
    /// <summary>
    /// The `ready` read-only property of the FontFaceSet interface returns a Promise that resolves to the given FontFaceSet.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontFaceSet/ready)
    /// </summary>
    ValueTask<IFontFaceSet> Ready { get; }
    /// <summary>
    /// The **`status`** read-only property of the FontFaceSet interface returns the loading state of the fonts in the set.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontFaceSet/status)
    /// </summary>
    FontFaceSetLoadStatus Status { get; }

    /// <summary>
    /// The `check()` method of the FontFaceSet returns `true` if you can render some text using the given font specification without attempting to use any fonts in this `FontFaceSet` that are not yet fully loaded.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontFaceSet/check)
    /// </summary>
    bool Check(string font, string text = default);

    /// <summary>
    /// The `load()` method of the FontFaceSet forces all the fonts given in parameters to be loaded.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/FontFaceSet/load)
    /// </summary>
    ValueTask<IFontFace[]> LoadAsync(string font, string text = default);

    void ForEach(Action<IFontFace, IFontFace, IFontFaceSet> callbackfn, object thisArg = default);

    void AddEventListener(object type, object listener, object options = default);

    void AddEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);

    void RemoveEventListener(object type, object listener, object options = default);

    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, object options = default);
}
