// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The `MediaQueryListEvent` object stores information on the changes that have happened to a MediaQueryList object — instances are available as the event object on a function referenced by a MediaQueryList.change_event event.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaQueryListEvent)
/// </summary>
public partial interface IMediaQueryListEvent : IEvent
{
    /// <summary>
    /// The **`matches`** read-only property of the `true` if the document currently matches the media query list, or `false` if not.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaQueryListEvent/matches)
    /// </summary>
    bool Matches { get; }
    /// <summary>
    /// The **`media`** read-only property of the a serialized media query.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaQueryListEvent/media)
    /// </summary>
    string Media { get; }
}
