#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Blazor.DOM;

[JsonConverter(typeof(JsonStringEnumConverter<KeyUsage>))]
public enum KeyUsage
{
    [EnumMember(Value = "decrypt")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("decrypt")]
    #endif
    Decrypt,

    [EnumMember(Value = "deriveBits")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("deriveBits")]
    #endif
    DeriveBits,

    [EnumMember(Value = "deriveKey")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("deriveKey")]
    #endif
    DeriveKey,

    [EnumMember(Value = "encrypt")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("encrypt")]
    #endif
    Encrypt,

    [EnumMember(Value = "sign")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("sign")]
    #endif
    Sign,

    [EnumMember(Value = "unwrapKey")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("unwrapKey")]
    #endif
    UnwrapKey,

    [EnumMember(Value = "verify")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("verify")]
    #endif
    Verify,

    [EnumMember(Value = "wrapKey")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("wrapKey")]
    #endif
    WrapKey
}
