#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM.Namespaces.WebAssembly;

public partial interface IModuleExportDescriptor : global::Microsoft.JSInterop.IDomDispatchProxy
{
    [global::Microsoft.JSInterop.DomAccessor("kind", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "ImportExportKind", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("kind", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "ImportExportKind", Nullable = false, Streamable = false, StructuredClone = true)]
    global::Blazor.DOM.Namespaces.WebAssembly.ImportExportKind Kind
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<global::Blazor.DOM.Namespaces.WebAssembly.ImportExportKind>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "kind", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("ImportExportKind", nullable: false));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "kind", value);
    }

    [global::Microsoft.JSInterop.DomAccessor("name", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("name", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    string Name
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "name", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "name", value);
    }
}


public sealed class ModuleExportDescriptorDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IModuleExportDescriptor
{
}
