// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

namespace Blazor.DOM.AdvancedTypes;

[JsonConverter(typeof(AutoFillSectionStringPatternShape_12d8cc39efJsonConverter))]
public readonly record struct AutoFillSectionStringPatternShape_12d8cc39ef : global::Microsoft.JSInterop.ITypeScriptStringValue
{
    private static readonly Regex Pattern = new("^section-[\\s\\S]*$", RegexOptions.CultureInvariant | RegexOptions.NonBacktracking);
    public string Value { get; }

    public AutoFillSectionStringPatternShape_12d8cc39ef(string value)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (!Pattern.IsMatch(value)) throw new ArgumentException("Value does not match TypeScript pattern `section-${string}`.", nameof(value));
        Value = value;
    }

    public static AutoFillSectionStringPatternShape_12d8cc39ef Parse(string value) => new(value);
    public static bool TryParse(string? value, out AutoFillSectionStringPatternShape_12d8cc39ef result)
    {
        if (value is not null && Pattern.IsMatch(value))
        {
            result = new AutoFillSectionStringPatternShape_12d8cc39ef(value);
            return true;
        }
        result = default;
        return false;
    }
    public override string ToString() => Value;
}

internal sealed class AutoFillSectionStringPatternShape_12d8cc39efJsonConverter : JsonConverter<AutoFillSectionStringPatternShape_12d8cc39ef>
{
    public override AutoFillSectionStringPatternShape_12d8cc39ef Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => new(reader.GetString() ?? throw new JsonException("Pattern value cannot be null."));
    public override void Write(Utf8JsonWriter writer, AutoFillSectionStringPatternShape_12d8cc39ef value, JsonSerializerOptions options) => writer.WriteStringValue(value.Value);
}
