#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.JSInterop;

namespace Blazor.DOM.AdvancedTypes;

// TypeScript union: number | DOMPointInit | (number | DOMPointInit)[]
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public readonly struct CanvasPathUnionShape_65f0fa7449 : IEquatable<CanvasPathUnionShape_65f0fa7449>, IDomUnionValue
{
    public enum ArmKind : byte
    {
        Uninitialized = 0,
        Number = 1,
        DOMPointInit = 2,
        Array = 3
    }

    private readonly object? _value;
    public ArmKind Kind { get; }
    public bool IsInitialized => Kind != ArmKind.Uninitialized;
    int IDomUnionValue.ArmIndex => (int)Kind;
    DomTransportDescriptor IDomUnionValue.SelectedTransport => Kind switch
    {
        ArmKind.Number => DomTransportDescriptor.JsonValue("number", nullable: false),
        ArmKind.DOMPointInit => DomTransportDescriptor.JsonValue("DOMPointInit", nullable: false),
        ArmKind.Array => DomTransportDescriptor.JsonValue("(number | DOMPointInit)[]", nullable: false),
        _ => DomTransportDescriptor.Unsupported("uninitialized union", "A default union value has no selected arm."),
    };
    private CanvasPathUnionShape_65f0fa7449(ArmKind kind, object? value) => (Kind, _value) = (kind, value);

    public static CanvasPathUnionShape_65f0fa7449 FromNumber(double value) => new(ArmKind.Number, value);
    public bool IsNumber => Kind == ArmKind.Number;
    public double GetNumber() => Kind == ArmKind.Number ? (double)_value! : throw new InvalidOperationException($"The union contains '{Kind}', not 'Number'.");
    public bool TryGetNumber([MaybeNullWhen(false)] out double value)
    {
        if (Kind == ArmKind.Number)
        {
            value = (double)_value!;
            return true;
        }
        value = default;
        return false;
    }

    public static CanvasPathUnionShape_65f0fa7449 FromDOMPointInit(DOMPointInit value) => new(ArmKind.DOMPointInit, value);
    public bool IsDOMPointInit => Kind == ArmKind.DOMPointInit;
    public DOMPointInit GetDOMPointInit() => Kind == ArmKind.DOMPointInit ? (DOMPointInit)_value! : throw new InvalidOperationException($"The union contains '{Kind}', not 'DOMPointInit'.");
    public bool TryGetDOMPointInit([MaybeNullWhen(false)] out DOMPointInit value)
    {
        if (Kind == ArmKind.DOMPointInit)
        {
            value = (DOMPointInit)_value!;
            return true;
        }
        value = default;
        return false;
    }

    public static CanvasPathUnionShape_65f0fa7449 FromArray(global::Blazor.DOM.AdvancedTypes.CanvasPathUnionShape_76d0ac22d5[] value) => new(ArmKind.Array, value);
    public bool IsArray => Kind == ArmKind.Array;
    public global::Blazor.DOM.AdvancedTypes.CanvasPathUnionShape_76d0ac22d5[] GetArray() => Kind == ArmKind.Array ? (global::Blazor.DOM.AdvancedTypes.CanvasPathUnionShape_76d0ac22d5[])_value! : throw new InvalidOperationException($"The union contains '{Kind}', not 'Array'.");
    public bool TryGetArray([MaybeNullWhen(false)] out global::Blazor.DOM.AdvancedTypes.CanvasPathUnionShape_76d0ac22d5[] value)
    {
        if (Kind == ArmKind.Array)
        {
            value = (global::Blazor.DOM.AdvancedTypes.CanvasPathUnionShape_76d0ac22d5[])_value!;
            return true;
        }
        value = default;
        return false;
    }

    public bool Equals(CanvasPathUnionShape_65f0fa7449 other) => Kind == other.Kind && EqualityComparer<object?>.Default.Equals(_value, other._value);
    public override bool Equals(object? obj) => obj is CanvasPathUnionShape_65f0fa7449 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(Kind, _value);
    public static bool operator ==(CanvasPathUnionShape_65f0fa7449 left, CanvasPathUnionShape_65f0fa7449 right) => left.Equals(right);
    public static bool operator !=(CanvasPathUnionShape_65f0fa7449 left, CanvasPathUnionShape_65f0fa7449 right) => !left.Equals(right);
    public override string ToString() => Kind switch
    {
        ArmKind.Uninitialized => "(uninitialized)",
        ArmKind.Number => _value?.ToString() ?? "null",
        ArmKind.DOMPointInit => _value?.ToString() ?? "null",
        ArmKind.Array => _value?.ToString() ?? "null",
        _ => "(invalid)",
    };
    private string DebuggerDisplay => $"{Kind}: {ToString()}";
}
