// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Blazor.DOM.AdvancedTypes;

[JsonConverter(typeof(JsonStringEnumConverter<DocumentStringShape_78ae7eab91>))]
public enum DocumentStringShape_78ae7eab91
{
    [EnumMember(Value = "PageRevealEvent")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("PageRevealEvent")]
    #endif
    PageRevealEvent
}
