// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Blazor.DOM.AdvancedTypes;

[JsonConverter(typeof(JsonStringEnumConverter<DocumentStringShape_b9a4fb9d61>))]
public enum DocumentStringShape_b9a4fb9d61
{
    [EnumMember(Value = "PaymentRequestUpdateEvent")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("PaymentRequestUpdateEvent")]
    #endif
    PaymentRequestUpdateEvent
}
