// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Blazor.DOM.AdvancedTypes;

[JsonConverter(typeof(URLSearchParamsTupleShape_acc9ba908bJsonConverter))]
public sealed record URLSearchParamsTupleShape_acc9ba908b
{
    public required string Item1 { get; init; }
    public required string Item2 { get; init; }
}

internal sealed class URLSearchParamsTupleShape_acc9ba908bJsonConverter : JsonConverter<URLSearchParamsTupleShape_acc9ba908b>
{
    public override URLSearchParamsTupleShape_acc9ba908b Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.StartArray)
            throw new JsonException("Expected a JSON array for a TypeScript tuple.");
        reader.Read();
        if (reader.TokenType == JsonTokenType.EndArray)
            throw new JsonException("TypeScript tuple has too few elements.");
        var value0 = JsonSerializer.Deserialize<string>(ref reader, options)!;
        reader.Read();
        if (reader.TokenType == JsonTokenType.EndArray)
            throw new JsonException("TypeScript tuple has too few elements.");
        var value1 = JsonSerializer.Deserialize<string>(ref reader, options)!;
        reader.Read();
        if (reader.TokenType != JsonTokenType.EndArray)
            throw new JsonException("TypeScript tuple has too many elements.");
        return new URLSearchParamsTupleShape_acc9ba908b
        {
            Item1 = value0,
            Item2 = value1,
        };
    }

    public override void Write(Utf8JsonWriter writer, URLSearchParamsTupleShape_acc9ba908b value, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, value.Item1, options);
        JsonSerializer.Serialize(writer, value.Item2, options);
        writer.WriteEndArray();
    }
}
