#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.JSInterop;

namespace Blazor.DOM.AdvancedTypes;

// TypeScript union: number | boolean
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public readonly struct WebGLRenderingContextBaseUnionShape_138d147677 : IEquatable<WebGLRenderingContextBaseUnionShape_138d147677>, IDomUnionValue
{
    public enum ArmKind : byte
    {
        Uninitialized = 0,
        GLint = 1,
        GLboolean = 2
    }

    private readonly object? _value;
    public ArmKind Kind { get; }
    public bool IsInitialized => Kind != ArmKind.Uninitialized;
    int IDomUnionValue.ArmIndex => (int)Kind;
    DomTransportDescriptor IDomUnionValue.SelectedTransport => Kind switch
    {
        ArmKind.GLint => DomTransportDescriptor.JsonValue("number", nullable: false),
        ArmKind.GLboolean => DomTransportDescriptor.JsonValue("boolean", nullable: false),
        _ => DomTransportDescriptor.Unsupported("uninitialized union", "A default union value has no selected arm."),
    };
    private WebGLRenderingContextBaseUnionShape_138d147677(ArmKind kind, object? value) => (Kind, _value) = (kind, value);

    public static WebGLRenderingContextBaseUnionShape_138d147677 FromGLint(int value) => new(ArmKind.GLint, value);
    public bool IsGLint => Kind == ArmKind.GLint;
    public int GetGLint() => Kind == ArmKind.GLint ? (int)_value! : throw new InvalidOperationException($"The union contains '{Kind}', not 'GLint'.");
    public bool TryGetGLint([MaybeNullWhen(false)] out int value)
    {
        if (Kind == ArmKind.GLint)
        {
            value = (int)_value!;
            return true;
        }
        value = default;
        return false;
    }

    public static WebGLRenderingContextBaseUnionShape_138d147677 FromGLboolean(bool value) => new(ArmKind.GLboolean, value);
    public bool IsGLboolean => Kind == ArmKind.GLboolean;
    public bool GetGLboolean() => Kind == ArmKind.GLboolean ? (bool)_value! : throw new InvalidOperationException($"The union contains '{Kind}', not 'GLboolean'.");
    public bool TryGetGLboolean([MaybeNullWhen(false)] out bool value)
    {
        if (Kind == ArmKind.GLboolean)
        {
            value = (bool)_value!;
            return true;
        }
        value = default;
        return false;
    }

    public bool Equals(WebGLRenderingContextBaseUnionShape_138d147677 other) => Kind == other.Kind && EqualityComparer<object?>.Default.Equals(_value, other._value);
    public override bool Equals(object? obj) => obj is WebGLRenderingContextBaseUnionShape_138d147677 other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(Kind, _value);
    public static bool operator ==(WebGLRenderingContextBaseUnionShape_138d147677 left, WebGLRenderingContextBaseUnionShape_138d147677 right) => left.Equals(right);
    public static bool operator !=(WebGLRenderingContextBaseUnionShape_138d147677 left, WebGLRenderingContextBaseUnionShape_138d147677 right) => !left.Equals(right);
    public override string ToString() => Kind switch
    {
        ArmKind.Uninitialized => "(uninitialized)",
        ArmKind.GLint => _value?.ToString() ?? "null",
        ArmKind.GLboolean => _value?.ToString() ?? "null",
        _ => "(invalid)",
    };
    private string DebuggerDisplay => $"{Kind}: {ToString()}";
}
