// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Blazor.DOM.AdvancedTypes;

[JsonConverter(typeof(JsonStringEnumConverter<WebGLRenderingContextBaseStringShape_4c92a7ff14>))]
public enum WebGLRenderingContextBaseStringShape_4c92a7ff14
{
    [EnumMember(Value = "OES_texture_float")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("OES_texture_float")]
    #endif
    OESTextureFloat
}
