#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Text.Json.Serialization;

namespace Blazor.DOM;

public record AudioDataInit
{
    [JsonPropertyName("data")]
    public required BufferSource Data { get; init; }

    [JsonPropertyName("format")]
    public required AudioSampleFormat Format { get; init; }

    [JsonPropertyName("numberOfChannels")]
    public required double NumberOfChannels { get; init; }

    [JsonPropertyName("numberOfFrames")]
    public required double NumberOfFrames { get; init; }

    [JsonPropertyName("sampleRate")]
    public required double SampleRate { get; init; }

    [JsonPropertyName("timestamp")]
    public required double Timestamp { get; init; }

    [JsonPropertyName("transfer")]
    public global::Microsoft.JSInterop.IBrowserArray<byte[]>? Transfer { get; init; }
}
