#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Text.Json.Serialization;

namespace Blazor.DOM;

public record ConvolverOptions : AudioNodeOptions
{
    [JsonPropertyName("buffer")]
    public IAudioBuffer? Buffer { get; init; }

    [JsonPropertyName("disableNormalization")]
    public bool? DisableNormalization { get; init; }
}
