// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Text.Json.Serialization;

namespace Blazor.DOM;

/// <summary>
/// The `CSPViolationReportBody` interface is an extension of the Reporting API that represents the body of a Content Security Policy (CSP) violation report.
/// 
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSPViolationReportBody)
/// </summary>
public record CSPViolationReportBody : ReportBody
{
    // PROJECTION-FAILED: blockedURL -> Unsupported union type 'StringKeyword | null' at 'CSPViolationReportBody.blockedURL'. Mixed unions (non-nullable, non-all-string-literal) cannot be projected to C# without an explicit override.

    // PROJECTION-FAILED: columnNumber -> Unsupported union type 'NumberKeyword | null' at 'CSPViolationReportBody.columnNumber'. Mixed unions (non-nullable, non-all-string-literal) cannot be projected to C# without an explicit override.

    /// <summary>
    /// The **`disposition`** read-only property of the CSPViolationReportBody interface indicates whether the user agent is configured to enforce Content Security Policy (CSP) violations or only report them.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSPViolationReportBody/disposition)
    /// </summary>
    [JsonPropertyName("disposition")]
    public SecurityPolicyViolationEventDisposition Disposition { get; init; }

    /// <summary>
    /// The **`documentURL`** read-only property of the CSPViolationReportBody interface is a string that represents the URL of the document or worker that violated the Content Security Policy (CSP).
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSPViolationReportBody/documentURL)
    /// </summary>
    [JsonPropertyName("documentURL")]
    public string DocumentURL { get; init; }

    /// <summary>
    /// The **`effectiveDirective`** read-only property of the CSPViolationReportBody interface is a string that represents the effective Content Security Policy (CSP) directive that was violated.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSPViolationReportBody/effectiveDirective)
    /// </summary>
    [JsonPropertyName("effectiveDirective")]
    public string EffectiveDirective { get; init; }

    // PROJECTION-FAILED: lineNumber -> Unsupported union type 'NumberKeyword | null' at 'CSPViolationReportBody.lineNumber'. Mixed unions (non-nullable, non-all-string-literal) cannot be projected to C# without an explicit override.

    /// <summary>
    /// The **`originalPolicy`** read-only property of the CSPViolationReportBody interface is a string that represents the Content Security Policy (CSP) whose enforcement uncovered the violation.
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSPViolationReportBody/originalPolicy)
    /// </summary>
    [JsonPropertyName("originalPolicy")]
    public string OriginalPolicy { get; init; }

    // PROJECTION-FAILED: referrer -> Unsupported union type 'StringKeyword | null' at 'CSPViolationReportBody.referrer'. Mixed unions (non-nullable, non-all-string-literal) cannot be projected to C# without an explicit override.

    // PROJECTION-FAILED: sample -> Unsupported union type 'StringKeyword | null' at 'CSPViolationReportBody.sample'. Mixed unions (non-nullable, non-all-string-literal) cannot be projected to C# without an explicit override.

    // PROJECTION-FAILED: sourceFile -> Unsupported union type 'StringKeyword | null' at 'CSPViolationReportBody.sourceFile'. Mixed unions (non-nullable, non-all-string-literal) cannot be projected to C# without an explicit override.

    /// <summary>
    /// The **`statusCode`** read-only property of the CSPViolationReportBody interface is a number representing the HTTP status code of the response to the request that triggered a Content Security Policy (CSP) violation (when loading a window or worker).
    /// 
    /// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CSPViolationReportBody/statusCode)
    /// </summary>
    [JsonPropertyName("statusCode")]
    public double StatusCode { get; init; }
}
