#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Text.Json.Serialization;

namespace Blazor.DOM;

// TypeScript generic default: T = object.
public record MessageEventInit<T> : EventInit
{
    [JsonPropertyName("data")]
    public T? Data { get; init; }

    [JsonPropertyName("lastEventId")]
    public string? LastEventId { get; init; }

    [JsonPropertyName("origin")]
    public string? Origin { get; init; }

    [JsonPropertyName("ports")]
    public global::Microsoft.JSInterop.IBrowserArray<IMessagePort>? Ports { get; init; }

    [JsonPropertyName("source")]
    public MessageEventSource? Source { get; init; }
}
