#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Text.Json.Serialization;

namespace Blazor.DOM;

public record PeriodicWaveOptions : PeriodicWaveConstraints
{
    [JsonPropertyName("imag")]
    public global::Blazor.DOM.AdvancedTypes.AudioParamUnionShape_835e00e880? Imag { get; init; }

    [JsonPropertyName("real")]
    public global::Blazor.DOM.AdvancedTypes.AudioParamUnionShape_835e00e880? Real { get; init; }
}
