// Copyright (c) David Pine. All rights reserved.
// Licensed under the MIT License.

internal class CompilerOptions
{
    internal bool All { get; set; }
    internal bool AllowJs { get; set; }
    internal bool AllowNonTsExtensions { get; set; }
    internal bool AllowSyntheticDefaultImports { get; set; }
    internal bool AllowUnreachableCode { get; set; }
    internal bool AllowUnusedLabels { get; set; }
    internal bool AlwaysStrict { get; set; }
    internal string BaseUrl { get; set; }
    internal string Charset { get; set; }
    internal bool CheckJs { get; set; }
    internal string ConfigFilePath { get; set; }
    internal bool Declaration { get; set; }
    internal string DeclarationDir { get; set; }
    internal bool Diagnostics { get; set; }
    internal bool ExtendedDiagnostics { get; set; }
    internal bool DisableSizeLimit { get; set; }
    internal bool DownlevelIteration { get; set; }
    internal bool EmitBom { get; set; }
    internal bool EmitDecoratorMetadata { get; set; }
    internal bool ExperimentalDecorators { get; set; }
    internal bool ForceConsistentCasingInFileNames { get; set; }
    internal bool Help { get; set; }
    internal bool ImportHelpers { get; set; }
    internal bool Init { get; set; }
    internal bool InlineSourceMap { get; set; }
    internal bool InlineSources { get; set; }
    internal bool IsolatedModules { get; set; }
    internal JsxEmit Jsx { get; set; }
    internal string[] Lib { get; set; }
    internal bool ListEmittedFiles { get; set; }
    internal bool ListFiles { get; set; }
    internal string Locale { get; set; }
    internal string MapRoot { get; set; }
    internal int MaxNodeModuleJsDepth { get; set; }
    internal ModuleKind Module { get; set; }
    internal ModuleResolutionKind ModuleResolution { get; set; }
    internal NewLineKind NewLine { get; set; }
    internal bool NoEmit { get; set; }
    internal bool NoEmitForJsFiles { get; set; }
    internal bool NoEmitHelpers { get; set; }
    internal bool NoEmitOnError { get; set; }
    internal bool NoErrorTruncation { get; set; }
    internal bool NoFallthroughCasesInSwitch { get; set; }
    internal bool NoImplicitAny { get; set; }
    internal bool NoImplicitReturns { get; set; }
    internal bool NoImplicitThis { get; set; }
    internal bool NoUnusedLocals { get; set; }
    internal bool NoUnusedParameters { get; set; }
    internal bool NoImplicitUseStrict { get; set; }
    internal bool NoLib { get; set; }
    internal bool NoResolve { get; set; }
    internal string Out { get; set; }
    internal string OutDir { get; set; }
    internal string OutFile { get; set; }
    internal MapLike<string[]> Paths { get; set; }
    internal PluginImport[] Plugins { get; set; }
    internal bool PreserveConstEnums { get; set; }
    internal string Project { get; set; }
    internal DiagnosticStyle Pretty { get; set; }
    internal string ReactNamespace { get; set; }
    internal string JsxFactory { get; set; }
    internal bool RemoveComments { get; set; }
    internal string RootDir { get; set; }
    internal string[] RootDirs { get; set; }
    internal bool SkipLibCheck { get; set; }
    internal bool SkipDefaultLibCheck { get; set; }
    internal bool SourceMap { get; set; }
    internal string SourceRoot { get; set; }
    internal bool Strict { get; set; }
    internal bool StrictNullChecks { get; set; }
    internal bool StripInternal { get; set; }
    internal bool SuppressExcessPropertyErrors { get; set; }
    internal bool SuppressImplicitAnyIndexErrors { get; set; }
    internal bool SuppressOutputPathCheck { get; set; }
    internal ScriptTarget Target { get; set; }
    internal bool TraceResolution { get; set; }
    internal string[] Types { get; set; }
    internal string[] TypeRoots { get; set; }
    internal bool Version { get; set; }
    internal bool Watch { get; set; }
}