#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.JSInterop;

namespace Blazor.DOM;

// TypeScript union: OptionalPrefixToken = `${T} ` | ""
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public readonly struct OptionalPrefixToken<T> : IEquatable<OptionalPrefixToken<T>>, IDomUnionValue where T : global::Microsoft.JSInterop.ITypeScriptStringValue
{
    public enum ArmKind : byte
    {
        Uninitialized = 0,
        templateLiteral = 1,
        Literal__ = 2
    }

    private readonly object? _value;
    public ArmKind Kind { get; }
    public bool IsInitialized => Kind != ArmKind.Uninitialized;
    int IDomUnionValue.ArmIndex => (int)Kind;
    DomTransportDescriptor IDomUnionValue.SelectedTransport => Kind switch
    {
        ArmKind.templateLiteral => DomTransportDescriptor.JsonValue("`${T} `", nullable: false),
        ArmKind.Literal__ => DomTransportDescriptor.JsonValue("\"\"", nullable: false),
        _ => DomTransportDescriptor.Unsupported("uninitialized union", "A default union value has no selected arm."),
    };
    private OptionalPrefixToken(ArmKind kind, object? value) => (Kind, _value) = (kind, value);

    public static OptionalPrefixToken<T> FromtemplateLiteral(global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringPatternShape_80b726c442 value) => new(ArmKind.templateLiteral, value);
    public bool IstemplateLiteral => Kind == ArmKind.templateLiteral;
    public global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringPatternShape_80b726c442 GettemplateLiteral() => Kind == ArmKind.templateLiteral ? (global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringPatternShape_80b726c442)_value! : throw new InvalidOperationException($"The union contains '{Kind}', not 'templateLiteral'.");
    public bool TryGettemplateLiteral([MaybeNullWhen(false)] out global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringPatternShape_80b726c442 value)
    {
        if (Kind == ArmKind.templateLiteral)
        {
            value = (global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringPatternShape_80b726c442)_value!;
            return true;
        }
        value = default;
        return false;
    }

    public static OptionalPrefixToken<T> FromLiteral__(global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringShape_432481e456 value) => new(ArmKind.Literal__, value);
    public bool IsLiteral__ => Kind == ArmKind.Literal__;
    public global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringShape_432481e456 GetLiteral__() => Kind == ArmKind.Literal__ ? (global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringShape_432481e456)_value! : throw new InvalidOperationException($"The union contains '{Kind}', not 'Literal__'.");
    public bool TryGetLiteral__([MaybeNullWhen(false)] out global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringShape_432481e456 value)
    {
        if (Kind == ArmKind.Literal__)
        {
            value = (global::Blazor.DOM.AdvancedTypes.OptionalPrefixTokenStringShape_432481e456)_value!;
            return true;
        }
        value = default;
        return false;
    }

    public bool Equals(OptionalPrefixToken<T> other) => Kind == other.Kind && EqualityComparer<object?>.Default.Equals(_value, other._value);
    public override bool Equals(object? obj) => obj is OptionalPrefixToken<T> other && Equals(other);
    public override int GetHashCode() => HashCode.Combine(Kind, _value);
    public static bool operator ==(OptionalPrefixToken<T> left, OptionalPrefixToken<T> right) => left.Equals(right);
    public static bool operator !=(OptionalPrefixToken<T> left, OptionalPrefixToken<T> right) => !left.Equals(right);
    public override string ToString() => Kind switch
    {
        ArmKind.Uninitialized => "(uninitialized)",
        ArmKind.templateLiteral => _value?.ToString() ?? "null",
        ArmKind.Literal__ => _value?.ToString() ?? "null",
        _ => "(invalid)",
    };
    private string DebuggerDisplay => $"{Kind}: {ToString()}";
}
