#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`Event`** interface represents an event which takes place on an `EventTarget`.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event)
/// </summary>
public partial interface IEvent
{
    /// <summary>
/// The **`bubbles`** read-only property of the Event interface indicates whether the event bubbles up through the DOM tree or not.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/bubbles)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("bubbles", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
bool Bubbles { get; }

    /// <summary>
/// The **`cancelBubble`** property of the Event interface is deprecated.
/// </summary>
[Obsolete]
[global::Microsoft.JSInterop.DomAccessor("cancelBubble", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("cancelBubble", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
bool CancelBubble { get; set; }

    /// <summary>
/// The **`cancelable`** read-only property of the Event interface indicates whether the event can be canceled, and therefore prevented as if the event never happened.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/cancelable)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("cancelable", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
bool Cancelable { get; }

    /// <summary>
/// The read-only **`composed`** property of the or not the event will propagate across the shadow DOM boundary into the standard DOM.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/composed)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("composed", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
bool Composed { get; }

    /// <summary>
/// The **`currentTarget`** read-only property of the Event interface identifies the element to which the event handler has been attached.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/currentTarget)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("currentTarget", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "EventTarget | null", Nullable = true, Streamable = false, StructuredClone = false)]
IEventTarget? CurrentTarget { get; }

    /// <summary>
/// The **`defaultPrevented`** read-only property of the Event interface returns a boolean value indicating whether or not the call to Event.preventDefault() canceled the event.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/defaultPrevented)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("defaultPrevented", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
bool DefaultPrevented { get; }

    /// <summary>
/// The **`eventPhase`** read-only property of the being evaluated.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/eventPhase)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("eventPhase", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
double EventPhase { get; }

    /// <summary>
/// The **`isTrusted`** read-only property of the when the event was generated by the user agent (including via user actions and programmatic methods such as HTMLElement.focus()), and `false` when the event was dispatched via The only exception is the `click` event, which initializes the `isTrusted` property to `false` in user agents.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/isTrusted)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("isTrusted", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
bool IsTrusted { get; }

    /// <summary>
/// The Event property **`returnValue`** indicates whether the default action for this event has been prevented or not.
/// </summary>
[Obsolete]
[global::Microsoft.JSInterop.DomAccessor("returnValue", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("returnValue", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
bool ReturnValue { get; set; }

    /// <summary>
/// The deprecated **`Event.srcElement`** is an alias for the Event.target property.
/// </summary>
[Obsolete]
[global::Microsoft.JSInterop.DomAccessor("srcElement", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "EventTarget | null", Nullable = true, Streamable = false, StructuredClone = false)]
IEventTarget? SrcElement { get; }

    /// <summary>
/// The read-only **`target`** property of the dispatched.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/target)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("target", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "EventTarget | null", Nullable = true, Streamable = false, StructuredClone = false)]
IEventTarget? Target { get; }

    /// <summary>
/// The **`timeStamp`** read-only property of the Event interface returns the time (in milliseconds) at which the event was created.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/timeStamp)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("timeStamp", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
double TimeStamp { get; }

    /// <summary>
/// The **`type`** read-only property of the Event interface returns a string containing the event's type.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/type)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("type", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
string Type { get; }

    [global::Microsoft.JSInterop.DomAccessor("NONE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "0", Nullable = false, Streamable = false, StructuredClone = true)]
double NONE { get; }

    [global::Microsoft.JSInterop.DomAccessor("CAPTURING_PHASE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "1", Nullable = false, Streamable = false, StructuredClone = true)]
double CAPTURINGPHASE { get; }

    [global::Microsoft.JSInterop.DomAccessor("AT_TARGET", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "2", Nullable = false, Streamable = false, StructuredClone = true)]
double ATTARGET { get; }

    [global::Microsoft.JSInterop.DomAccessor("BUBBLING_PHASE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "3", Nullable = false, Streamable = false, StructuredClone = true)]
double BUBBLINGPHASE { get; }

    /// <summary>
/// The **`composedPath()`** method of the Event interface returns the event's path which is an array of the objects on which listeners will be invoked.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/composedPath)
/// </summary>
global::Microsoft.JSInterop.IBrowserArray<IEventTarget> ComposedPath();

    /// <summary>
/// The **`Event.initEvent()`** method is used to initialize the value of an event created using Document.createEvent().
/// </summary>
[Obsolete]
void InitEvent(string type, bool bubbles = default, bool cancelable = default);

    /// <summary>
/// The **`preventDefault()`** method of the Event interface tells the user agent that if the event does not get explicitly handled, its default action should not be taken as it normally would be.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/preventDefault)
/// </summary>
void PreventDefault();

    /// <summary>
/// The **`stopImmediatePropagation()`** method of the If several listeners are attached to the same element for the same event type, they are called in the order in which they were added.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/stopImmediatePropagation)
/// </summary>
void StopImmediatePropagation();

    /// <summary>
/// The **`stopPropagation()`** method of the Event interface prevents further propagation of the current event in the capturing and bubbling phases.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/stopPropagation)
/// </summary>
void StopPropagation();
}
