#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public delegate void ResizeObserverCallback(global::Microsoft.JSInterop.IBrowserArray<IResizeObserverEntry> entries, IResizeObserver observer);
