#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IFontFaceFactory
{
    IFontFace Prototype { get; set; }

    IFontFace Create(string family, global::Blazor.DOM.AdvancedTypes.FontFaceUnionShape_8d49835c6b source, FontFaceDescriptors? descriptors = default);
}
