#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IMediaStreamFactory
{
    IMediaStream Prototype { get; set; }

    IMediaStream Create();

    IMediaStream Create(IMediaStream stream);

    IMediaStream Create(global::Microsoft.JSInterop.IBrowserArray<IMediaStreamTrack> tracks);
}
