#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ISVGFEFuncRElementFactory
{
    ISVGFEFuncRElement Prototype { get; set; }

    ISVGFEFuncRElement Create();
}
