#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Blazor.DOM;

[JsonConverter(typeof(JsonStringEnumConverter<DocumentReadyState>))]
public enum DocumentReadyState
{
    [EnumMember(Value = "complete")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("complete")]
    #endif
    Complete,

    [EnumMember(Value = "interactive")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("interactive")]
    #endif
    Interactive,

    [EnumMember(Value = "loading")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("loading")]
    #endif
    Loading
}
