#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Blazor.DOM;

[JsonConverter(typeof(JsonStringEnumConverter<OpusBitstreamFormat>))]
public enum OpusBitstreamFormat
{
    [EnumMember(Value = "ogg")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("ogg")]
    #endif
    Ogg,

    [EnumMember(Value = "opus")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("opus")]
    #endif
    Opus
}
