#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Blazor.DOM;

[JsonConverter(typeof(JsonStringEnumConverter<RTCPriorityType>))]
public enum RTCPriorityType
{
    [EnumMember(Value = "high")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("high")]
    #endif
    High,

    [EnumMember(Value = "low")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("low")]
    #endif
    Low,

    [EnumMember(Value = "medium")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("medium")]
    #endif
    Medium,

    [EnumMember(Value = "very-low")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("very-low")]
    #endif
    VeryLow
}
