#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Blazor.DOM;

[JsonConverter(typeof(JsonStringEnumConverter<WebTransportErrorSource>))]
public enum WebTransportErrorSource
{
    [EnumMember(Value = "session")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("session")]
    #endif
    Session,

    [EnumMember(Value = "stream")]
    #if NET9_0_OR_GREATER
    [JsonStringEnumMemberName("stream")]
    #endif
    Stream
}
