#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM.Namespaces.WebAssembly;

public partial interface ITableDescriptor : global::Microsoft.JSInterop.IDomDispatchProxy
{
    [global::Microsoft.JSInterop.DomAccessor("element", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "TableKind", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<global::Blazor.DOM.Namespaces.WebAssembly.TableKind> GetElementAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<global::Blazor.DOM.Namespaces.WebAssembly.TableKind>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "element", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("TableKind", nullable: false), cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("element", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "TableKind", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetElementAsync(global::Blazor.DOM.Namespaces.WebAssembly.TableKind value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "element", value, cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("initial", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double> GetInitialAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "initial", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("initial", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetInitialAsync(double value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "initial", value, cancellationToken);

    [global::Microsoft.JSInterop.DomAccessor("maximum", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = true, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask<double?> GetMaximumAsync(global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.GetPropertyAsync<double?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "maximum", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: true), cancellationToken);


    [global::Microsoft.JSInterop.DomAccessor("maximum", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = true, Streamable = false, StructuredClone = true)]
    global::System.Threading.Tasks.ValueTask SetMaximumAsync(double? value, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.SetPropertyAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "maximum", value, cancellationToken);
}


public sealed class TableDescriptorDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.DomProxyBase(reference, runtime, factory), ITableDescriptor
{
}
