#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`Cache`** interface provides a persistent storage mechanism for Request / Response object pairs that are cached in long lived memory.
/// Available only in secure contexts.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Cache)
/// </summary>
// Requires secure context (HTTPS).
public partial interface ICache : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`add()`** method of the Cache interface takes a URL, retrieves it, and adds the resulting response object to the given cache.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Cache/add)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:add`0<>(union(RequestInfo<>|URL<>):optional=False:rest=False)[clr:global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4]->ValueTask@transport:json-value:False:False:True:Promise<void>", "add", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "Promise<void>", Nullable = false, Promise = true, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomJavaScriptName("add")]
    global::System.Threading.Tasks.ValueTask AddAsync(global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4 request, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "add", [request], cancellationToken);

    /// <summary>
/// The **`addAll()`** method of the Cache interface takes an array of URLs, retrieves them, and adds the resulting response objects to the given cache.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Cache/addAll)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:addAll`0<>(RequestInfo<>[]:optional=False:rest=False)[clr:global::Microsoft.JSInterop.IBrowserArray<RequestInfo>]->ValueTask@transport:json-value:False:False:True:Promise<void>", "addAll", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "Promise<void>", Nullable = false, Promise = true, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomJavaScriptName("addAll")]
    global::System.Threading.Tasks.ValueTask AddAllAsync(global::Microsoft.JSInterop.IBrowserArray<RequestInfo> requests, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addAll", [requests], cancellationToken);

    /// <summary>
/// The **`delete()`** method of the Cache interface finds the Cache entry whose key is the request, and if found, deletes the Cache entry and returns a Promise that resolves to `true`.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Cache/delete)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:delete`0<>(union(RequestInfo<>|URL<>):optional=False:rest=False,CacheQueryOptions<>:optional=True:rest=False)[clr:global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4,CacheQueryOptions]->ValueTask<bool>@transport:json-value:False:False:True:Promise<boolean>", "delete", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "Promise<boolean>", Nullable = false, Promise = true, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomJavaScriptName("delete")]
    global::System.Threading.Tasks.ValueTask<bool> DeleteAsync(global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4 request, CacheQueryOptions? options = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<bool>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "delete", [request, options], global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("Promise<boolean>", nullable: false), cancellationToken);

    /// <summary>
/// The **`keys()`** method of the Cache interface returns a representing the keys of the Cache.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Cache/keys)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:keys`0<>(union(RequestInfo<>|URL<>):optional=True:rest=False,CacheQueryOptions<>:optional=True:rest=False)[clr:global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4,CacheQueryOptions]->ValueTask<global::Microsoft.JSInterop.IReadOnlyBrowserArray<IRequest>>@transport:unsupported:False:False:False:Promise<readonly Request[]>", "keys", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "Promise<readonly Request[]>", Nullable = false, Promise = true, Streamable = false, StructuredClone = false, UnsupportedReason = "Collection 'readonly Request[]' contains a non-JSON transport.")]
[global::Microsoft.JSInterop.DomJavaScriptName("keys")]
    global::System.Threading.Tasks.ValueTask<global::Microsoft.JSInterop.IReadOnlyBrowserArray<IRequest>> KeysAsync(global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4 request = default, CacheQueryOptions? options = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<global::Microsoft.JSInterop.IReadOnlyBrowserArray<IRequest>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "keys", [request, options], global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("Promise<readonly Request[]>", "Collection 'readonly Request[]' contains a non-JSON transport.", nullable: false), cancellationToken);

    /// <summary>
/// The **`match()`** method of the Cache interface returns a Promise that resolves to the Response associated with the first matching request in the Cache object.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Cache/match)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:match`0<>(union(RequestInfo<>|URL<>):optional=False:rest=False,CacheQueryOptions<>:optional=True:rest=False)[clr:global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4,CacheQueryOptions]->ValueTask<global::Blazor.DOM.AdvancedTypes.CacheUnionShape_1694ad008a>@transport:js-reference:True:False:False:Promise<Response | undefined>", "match", global::Microsoft.JSInterop.DomTransportKind.JsReference, "Promise<Response | undefined>", Nullable = true, Promise = true, Streamable = false, StructuredClone = false)]
[global::Microsoft.JSInterop.DomJavaScriptName("match")]
    global::System.Threading.Tasks.ValueTask<global::Blazor.DOM.AdvancedTypes.CacheUnionShape_1694ad008a> MatchAsync(global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4 request, CacheQueryOptions? options = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<global::Blazor.DOM.AdvancedTypes.CacheUnionShape_1694ad008a>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "match", [request, options], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("Promise<Response | undefined>", nullable: true, streamable: false, structuredClone: false), cancellationToken);

    /// <summary>
/// The **`matchAll()`** method of the Cache interface returns a Promise that resolves to an array of all matching responses in the Cache object.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Cache/matchAll)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:matchAll`0<>(union(RequestInfo<>|URL<>):optional=True:rest=False,CacheQueryOptions<>:optional=True:rest=False)[clr:global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4,CacheQueryOptions]->ValueTask<global::Microsoft.JSInterop.IReadOnlyBrowserArray<IResponse>>@transport:unsupported:False:False:False:Promise<readonly Response[]>", "matchAll", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "Promise<readonly Response[]>", Nullable = false, Promise = true, Streamable = false, StructuredClone = false, UnsupportedReason = "Collection 'readonly Response[]' contains a non-JSON transport.")]
[global::Microsoft.JSInterop.DomJavaScriptName("matchAll")]
    global::System.Threading.Tasks.ValueTask<global::Microsoft.JSInterop.IReadOnlyBrowserArray<IResponse>> MatchAllAsync(global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4 request = default, CacheQueryOptions? options = default, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeAsync<global::Microsoft.JSInterop.IReadOnlyBrowserArray<IResponse>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "matchAll", [request, options], global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("Promise<readonly Response[]>", "Collection 'readonly Response[]' contains a non-JSON transport.", nullable: false), cancellationToken);

    /// <summary>
/// The **`put()`** method of the Often, you will just want to Window/fetch one or more requests, then add the result straight to your cache.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Cache/put)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:put`0<>(union(RequestInfo<>|URL<>):optional=False:rest=False,Response<>:optional=False:rest=False)[clr:global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4,IResponse]->ValueTask@transport:json-value:False:False:True:Promise<void>", "put", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "Promise<void>", Nullable = false, Promise = true, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomJavaScriptName("put")]
    global::System.Threading.Tasks.ValueTask PutAsync(global::Blazor.DOM.AdvancedTypes.CacheUnionShape_c53da6bcf4 request, IResponse response, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "put", [request, response], cancellationToken);

    /// <summary>
/// The **`addAll()`** method of the Cache interface takes an array of URLs, retrieves them, and adds the resulting response objects to the given cache.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/Cache/addAll)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:addAll`0<>(Iterable<RequestInfo<>>:optional=False:rest=False)[clr:global::Microsoft.JSInterop.IBrowserIterable<RequestInfo>]->ValueTask@transport:json-value:False:False:True:Promise<void>", "addAll", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "Promise<void>", Nullable = false, Promise = true, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomJavaScriptName("addAll")]
    global::System.Threading.Tasks.ValueTask AddAllAsync(global::Microsoft.JSInterop.IBrowserIterable<RequestInfo> requests, global::System.Threading.CancellationToken cancellationToken = default) => global::Microsoft.JSInterop.DomDispatch.InvokeVoidAsync((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addAll", [requests], cancellationToken);
}


public sealed class CacheDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), ICache
{
}
