#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ICSSViewTransitionRule : ICSSRule, global::Microsoft.JSInterop.IDomDispatchProxy
{
    [global::Microsoft.JSInterop.DomAccessor("navigation", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    string Navigation
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "navigation", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("types", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "readonly string[]", Nullable = false, Streamable = false, StructuredClone = true)]
    string[] Types
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<string[]>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "types", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("readonly string[]", nullable: false));
    }
}


public sealed class CSSViewTransitionRuleDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), ICSSViewTransitionRule
{
}
