#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`DeviceOrientationEvent`** interface of the Device Orientation Events provides web developers with information from the physical orientation of the device running the web page.
/// Available only in secure contexts.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DeviceOrientationEvent)
/// </summary>
// Requires secure context (HTTPS).
public partial interface IDeviceOrientationEvent : IEvent, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`absolute`** read-only property of the DeviceOrientationEvent interface indicates whether or not the device is providing orientation data absolutely (that is, in reference to the Earth's coordinate frame) or using some arbitrary frame determined by the device.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DeviceOrientationEvent/absolute)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("absolute", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
    bool Absolute
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<bool>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "absolute", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("boolean", nullable: false));
    }

    /// <summary>
/// The **`alpha`** read-only property of the DeviceOrientationEvent interface returns the rotation of the device around the Z axis; that is, the number of degrees by which the device is being twisted around the center of the screen.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DeviceOrientationEvent/alpha)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("alpha", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | null", Nullable = true, Streamable = false, StructuredClone = true)]
    double? Alpha
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "alpha", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number | null", nullable: true));
    }

    /// <summary>
/// The **`beta`** read-only property of the DeviceOrientationEvent interface returns the rotation of the device around the X axis; that is, the number of degrees, ranged between -180 and 180, by which the device is tipped forward or backward.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DeviceOrientationEvent/beta)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("beta", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | null", Nullable = true, Streamable = false, StructuredClone = true)]
    double? Beta
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "beta", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number | null", nullable: true));
    }

    /// <summary>
/// The **`gamma`** read-only property of the DeviceOrientationEvent interface returns the rotation of the device around the Y axis; that is, the number of degrees, ranged between `-90` and `90`, by which the device is tilted left or right.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/DeviceOrientationEvent/gamma)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("gamma", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number | null", Nullable = true, Streamable = false, StructuredClone = true)]
    double? Gamma
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "gamma", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number | null", nullable: true));
    }
}


public sealed class DeviceOrientationEventDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IDeviceOrientationEvent
{
}
