#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IFormDataIterator<T> : global::Microsoft.JSInterop.IDomDispatchProxy
{
    [global::Microsoft.JSInterop.DomOperation("js:Symbol.iterator`0<>()[clr:]->IFormDataIterator<!0>@transport:unsupported:False:False:False:FormDataIterator<T>", "Symbol.iterator", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "FormDataIterator<T>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.")]
[global::Microsoft.JSInterop.DomSymbol(global::Microsoft.JSInterop.DomWellKnownSymbol.Iterator)]
    IFormDataIterator<T> SymbolIterator() => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<IFormDataIterator<T>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "Symbol.iterator", null, global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("FormDataIterator<T>", "Named TypeScript type 'FormDataIterator' has no reviewed DOM transport classification.", nullable: false));

    global::Microsoft.JSInterop.BrowserIteratorResult<T, global::Microsoft.JSInterop.BrowserUndefined> Next(object value) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<global::Microsoft.JSInterop.BrowserIteratorResult<T, global::Microsoft.JSInterop.BrowserUndefined>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "next", [value], global::Microsoft.JSInterop.DomDispatch.InferTransport<global::Microsoft.JSInterop.BrowserIteratorResult<T, global::Microsoft.JSInterop.BrowserUndefined>>("next"));
}


public sealed class FormDataIteratorDomProxy<T>(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IFormDataIterator<T>
{
}
