#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`GeolocationPositionError`** interface represents the reason of an error occurring when using the geolocating device.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/GeolocationPositionError)
/// </summary>
public partial interface IGeolocationPositionError : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`code`** read-only property of the GeolocationPositionError interface is an `unsigned short` representing the error code.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/GeolocationPositionError/code)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("code", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    double Code
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "code", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false));
    }

    /// <summary>
/// The **`message`** read-only property of the GeolocationPositionError interface returns a human-readable string describing the details of the error.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/GeolocationPositionError/message)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("message", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    string Message
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "message", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("PERMISSION_DENIED", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "1", Nullable = false, Streamable = false, StructuredClone = true)]
    double PERMISSIONDENIED
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "PERMISSION_DENIED", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("1", nullable: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("POSITION_UNAVAILABLE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "2", Nullable = false, Streamable = false, StructuredClone = true)]
    double POSITIONUNAVAILABLE
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "POSITION_UNAVAILABLE", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("2", nullable: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("TIMEOUT", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "3", Nullable = false, Streamable = false, StructuredClone = true)]
    double TIMEOUT
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "TIMEOUT", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("3", nullable: false));
    }
}


public sealed class GeolocationPositionErrorDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IGeolocationPositionError
{
}
