#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`HTMLLIElement`** interface exposes specific properties and methods (beyond those defined by regular HTMLElement interface it also has available to it by inheritance) for manipulating list elements.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLLIElement)
/// </summary>
[global::Microsoft.JSInterop.DomEventTarget("HTMLLIElement", "HTMLElementEventMap")]
public partial interface IHTMLLIElement : IHTMLElement, global::Microsoft.JSInterop.IDomDispatchProxy
{
    [Obsolete]
[global::Microsoft.JSInterop.DomAccessor("type", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("type", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    string Type
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "type", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "type", value);
    }

    /// <summary>
/// The **`value`** property of the HTMLLIElement interface indicates the ordinal position of the _list element_ inside a given ol.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/HTMLLIElement/value)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("value", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("value", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    double Value
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "value", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "value", value);
    }

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener]);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener, bool capture) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, capture]);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,AddEventListenerOptions]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener, AddEventListenerOptions? options) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, options]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, bool capture) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, capture]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,EventListenerOptions]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, EventListenerOptions? options) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, options]);
}


public sealed class HTMLLIElementDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IHTMLLIElement
{
}
