#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`MessageEvent`** interface represents a message received by a target object.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessageEvent)
/// </summary>
// TypeScript generic default: T = object.
public partial interface IMessageEvent<T> : IEvent, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`data`** read-only property of the The data sent by the message emitter; this can be any data type, depending on what originated this event.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessageEvent/data)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("data", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "T", Nullable = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'MessageEvent.T' has no reviewed DOM transport classification.")]
    T Data
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<T>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "data", global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("T", "Named TypeScript type 'MessageEvent.T' has no reviewed DOM transport classification.", nullable: false));
    }

    /// <summary>
/// The **`lastEventId`** read-only property of the unique ID for the event.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessageEvent/lastEventId)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("lastEventId", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    string LastEventId
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "lastEventId", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false));
    }

    /// <summary>
/// The **`origin`** read-only property of the origin of the message emitter.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessageEvent/origin)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("origin", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    string Origin
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "origin", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false));
    }

    /// <summary>
/// The **`ports`** read-only property of the containing all MessagePort objects sent with the message, in order.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessageEvent/ports)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("ports", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "readonly MessagePort[]", Nullable = false, Streamable = false, StructuredClone = false)]
    global::Microsoft.JSInterop.IReadOnlyBrowserArray<IMessagePort> Ports
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<global::Microsoft.JSInterop.IReadOnlyBrowserArray<IMessagePort>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "ports", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("readonly MessagePort[]", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// The **`source`** read-only property of the a WindowProxy, MessagePort, or a `MessageEventSource` (which can be a WindowProxy, message emitter.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/MessageEvent/source)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("source", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "MessageEventSource | null", Nullable = true, Streamable = false, StructuredClone = false, UnsupportedReason = "Union 'MessageEventSource | null' is unsupported: Union 'MessageEventSource' has incompatible transports: js-reference, transferable.")]
    MessageEventSource? Source
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<MessageEventSource?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "source", global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("MessageEventSource | null", "Union 'MessageEventSource | null' is unsupported: Union 'MessageEventSource' has incompatible transports: js-reference, transferable.", nullable: true));
    }

    [Obsolete]
[global::Microsoft.JSInterop.DomOperation("js:initMessageEvent`0<>(StringKeyword:optional=False:rest=False,BooleanKeyword:optional=True:rest=False,BooleanKeyword:optional=True:rest=False,AnyKeyword:optional=True:rest=False,StringKeyword:optional=True:rest=False,StringKeyword:optional=True:rest=False,union(MessageEventSource<>|NullKeyword:null):optional=True:rest=False,MessagePort<>[]:optional=True:rest=False)[clr:string,bool,bool,object,string,string,MessageEventSource?,global::Microsoft.JSInterop.IBrowserArray<IMessagePort>]->void@transport:json-value:False:False:True:void", "initMessageEvent", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void InitMessageEvent(string type, bool bubbles = default, bool cancelable = default, object? data = default, string? origin = default, string? lastEventId = default, MessageEventSource? source = default, global::Microsoft.JSInterop.IBrowserArray<IMessagePort>? ports = default) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "initMessageEvent", [type, bubbles, cancelable, data, origin, lastEventId, source, ports]);

    [Obsolete]
[global::Microsoft.JSInterop.DomOperation("js:initMessageEvent`0<>(StringKeyword:optional=False:rest=False,BooleanKeyword:optional=True:rest=False,BooleanKeyword:optional=True:rest=False,AnyKeyword:optional=True:rest=False,StringKeyword:optional=True:rest=False,StringKeyword:optional=True:rest=False,union(MessageEventSource<>|NullKeyword:null):optional=True:rest=False,Iterable<MessagePort<>>:optional=True:rest=False)[clr:string,bool,bool,object,string,string,MessageEventSource?,global::Microsoft.JSInterop.IBrowserIterable<IMessagePort>]->void@transport:json-value:False:False:True:void", "initMessageEvent", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void InitMessageEvent(string type, bool bubbles = default, bool cancelable = default, object? data = default, string? origin = default, string? lastEventId = default, MessageEventSource? source = default, global::Microsoft.JSInterop.IBrowserIterable<IMessagePort>? ports = default) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "initMessageEvent", [type, bubbles, cancelable, data, origin, lastEventId, source, ports]);
}


public sealed class MessageEventDomProxy<T>(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IMessageEvent<T>
{
}
