#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`PageTransitionEvent`** event object is available inside handler functions for the `pageshow` and `pagehide` events, fired when a document is being loaded or unloaded.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PageTransitionEvent)
/// </summary>
public partial interface IPageTransitionEvent : IEvent, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`persisted`** read-only property indicates if a webpage is loading from a cache.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PageTransitionEvent/persisted)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("persisted", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
    bool Persisted
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<bool>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "persisted", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("boolean", nullable: false));
    }
}


public sealed class PageTransitionEventDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IPageTransitionEvent
{
}
