#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`PermissionStatus`** interface of the Permissions API provides the state of an object and an event handler for monitoring changes to said state.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PermissionStatus)
/// </summary>
[global::Microsoft.JSInterop.DomEventTarget("PermissionStatus", "PermissionStatusEventMap")]
public partial interface IPermissionStatus : IEventTarget, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`name`** read-only property of the PermissionStatus interface returns the name of a requested permission.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PermissionStatus/name)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("name", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    string Name
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "name", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false));
    }

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PermissionStatus/change_event)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("onchange", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "((this: PermissionStatus, ev: Event) => any) | null", Nullable = true, Streamable = false, StructuredClone = false, UnsupportedReason = "Union '((this: PermissionStatus, ev: Event) => any) | null' is unsupported: TypeScript '(this: PermissionStatus, ev: Event) => any' has an ambiguous function shape.")]
[global::Microsoft.JSInterop.DomAccessor("onchange", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.Unsupported, "((this: PermissionStatus, ev: Event) => any) | null", Nullable = true, Streamable = false, StructuredClone = false, UnsupportedReason = "Union '((this: PermissionStatus, ev: Event) => any) | null' is unsupported: TypeScript '(this: PermissionStatus, ev: Event) => any' has an ambiguous function shape.")]
    Func<IEvent, object>? Onchange
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<Func<IEvent, object>?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "onchange", global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("((this: PermissionStatus, ev: Event) => any) | null", "Union '((this: PermissionStatus, ev: Event) => any) | null' is unsupported: TypeScript '(this: PermissionStatus, ev: Event) => any' has an ambiguous function shape.", nullable: true));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "onchange", value);
    }

    /// <summary>
/// The **`state`** read-only property of the This property returns one of `'granted'`, `'denied'`, or `'prompt'`.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PermissionStatus/state)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("state", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "PermissionState", Nullable = false, Streamable = false, StructuredClone = true)]
    PermissionState State
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<PermissionState>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "state", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("PermissionState", nullable: false));
    }

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener]);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener, bool capture) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, capture]);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,AddEventListenerOptions]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener, AddEventListenerOptions? options) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, options]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, bool capture) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, capture]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,EventListenerOptions]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, EventListenerOptions? options) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, options]);
}


public sealed class PermissionStatusDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IPermissionStatus
{
}
