#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`PushSubscriptionOptions`** interface of the Push API represents the options associated with a push subscription.
/// Available only in secure contexts.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PushSubscriptionOptions)
/// </summary>
// Requires secure context (HTTPS).
public partial interface IPushSubscriptionOptions : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`applicationServerKey`** read-only property of the PushSubscriptionOptions interface contains the public key used by the push server.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PushSubscriptionOptions/applicationServerKey)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("applicationServerKey", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.Binary, "ArrayBuffer | null", Nullable = true, Streamable = true, StructuredClone = true)]
    byte[]? ApplicationServerKey
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<byte[]?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "applicationServerKey", global::Microsoft.JSInterop.DomTransportDescriptor.Binary("ArrayBuffer | null", nullable: true, streamable: true));
    }

    /// <summary>
/// The **`userVisibleOnly`** read-only property of the PushSubscriptionOptions interface indicates if the returned push subscription will only be used for messages whose effect is made visible to the user.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/PushSubscriptionOptions/userVisibleOnly)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("userVisibleOnly", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Streamable = false, StructuredClone = true)]
    bool UserVisibleOnly
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<bool>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "userVisibleOnly", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("boolean", nullable: false));
    }
}


public sealed class PushSubscriptionOptionsDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IPushSubscriptionOptions
{
}
