#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`StylePropertyMapReadOnly`** interface of the CSS Typed Object Model API provides a read-only representation of a CSS declaration block that is an alternative to CSSStyleDeclaration.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/StylePropertyMapReadOnly)
/// </summary>
public partial interface IStylePropertyMapReadOnly : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`size`** read-only property of the containing the size of the `StylePropertyMapReadOnly` object.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/StylePropertyMapReadOnly/size)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("size", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    double Size
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "size", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false));
    }

    /// <summary>
/// The **`get()`** method of the object for the first value of the specified property.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/StylePropertyMapReadOnly/get)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:get`0<>(StringKeyword:optional=False:rest=False)[clr:string]->global::Blazor.DOM.AdvancedTypes.StylePropertyMapReadOnlyUnionShape_34245a79fa@transport:js-reference:True:False:False:CSSStyleValue | undefined", "get", global::Microsoft.JSInterop.DomTransportKind.JsReference, "CSSStyleValue | undefined", Nullable = true, Promise = false, Streamable = false, StructuredClone = false)]
    global::Blazor.DOM.AdvancedTypes.StylePropertyMapReadOnlyUnionShape_34245a79fa Get(string property) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<global::Blazor.DOM.AdvancedTypes.StylePropertyMapReadOnlyUnionShape_34245a79fa>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "get", [property], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("CSSStyleValue | undefined", nullable: true, streamable: false, structuredClone: false));

    /// <summary>
/// The **`getAll()`** method of the ```js-nolint getAll(property) ``` - `property` - : The name of the property to retrieve all values of.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/StylePropertyMapReadOnly/getAll)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:getAll`0<>(StringKeyword:optional=False:rest=False)[clr:string]->global::Microsoft.JSInterop.IBrowserArray<ICSSStyleValue>@transport:js-reference:False:False:False:CSSStyleValue[]", "getAll", global::Microsoft.JSInterop.DomTransportKind.JsReference, "CSSStyleValue[]", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    global::Microsoft.JSInterop.IBrowserArray<ICSSStyleValue> GetAll(string property) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<global::Microsoft.JSInterop.IBrowserArray<ICSSStyleValue>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "getAll", [property], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("CSSStyleValue[]", nullable: false, streamable: false, structuredClone: false));

    /// <summary>
/// The **`has()`** method of the property is in the `StylePropertyMapReadOnly` object.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/StylePropertyMapReadOnly/has)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:has`0<>(StringKeyword:optional=False:rest=False)[clr:string]->bool@transport:json-value:False:False:True:boolean", "has", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "boolean", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    bool Has(string property) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<bool>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "has", [property], global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("boolean", nullable: false));

    [global::Microsoft.JSInterop.DomOperation("js:forEach`0<>(function:(value: CSSStyleValue[], key: string, parent: StylePropertyMapReadOnly) => void:optional=False:rest=False,AnyKeyword:optional=True:rest=False)[clr:Action<global::Microsoft.JSInterop.IBrowserArray<ICSSStyleValue>, string, IStylePropertyMapReadOnly>,object]->void@transport:json-value:False:False:True:void", "forEach", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void ForEach(Action<global::Microsoft.JSInterop.IBrowserArray<ICSSStyleValue>, string, IStylePropertyMapReadOnly> callbackfn, object? thisArg = default) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "forEach", [callbackfn, thisArg]);

    [global::Microsoft.JSInterop.DomOperation("js:Symbol.iterator`0<>()[clr:]->IStylePropertyMapReadOnlyIterator<global::Blazor.DOM.AdvancedTypes.StylePropertyMapReadOnlyReferenceTupleShape_1272b75801>@transport:unsupported:False:False:False:StylePropertyMapReadOnlyIterator<[string, Iterable<CSSStyleValue>]>", "Symbol.iterator", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "StylePropertyMapReadOnlyIterator<[string, Iterable<CSSStyleValue>]>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'StylePropertyMapReadOnlyIterator' has no reviewed DOM transport classification.")]
[global::Microsoft.JSInterop.DomSymbol(global::Microsoft.JSInterop.DomWellKnownSymbol.Iterator)]
    IStylePropertyMapReadOnlyIterator<global::Blazor.DOM.AdvancedTypes.StylePropertyMapReadOnlyReferenceTupleShape_1272b75801> SymbolIterator() => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<IStylePropertyMapReadOnlyIterator<global::Blazor.DOM.AdvancedTypes.StylePropertyMapReadOnlyReferenceTupleShape_1272b75801>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "Symbol.iterator", null, global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("StylePropertyMapReadOnlyIterator<[string, Iterable<CSSStyleValue>]>", "Named TypeScript type 'StylePropertyMapReadOnlyIterator' has no reviewed DOM transport classification.", nullable: false));

    [global::Microsoft.JSInterop.DomOperation("js:entries`0<>()[clr:]->IStylePropertyMapReadOnlyIterator<global::Blazor.DOM.AdvancedTypes.StylePropertyMapReadOnlyReferenceTupleShape_5d666fed88>@transport:unsupported:False:False:False:StylePropertyMapReadOnlyIterator<[string, Iterable<CSSStyleValue>]>", "entries", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "StylePropertyMapReadOnlyIterator<[string, Iterable<CSSStyleValue>]>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'StylePropertyMapReadOnlyIterator' has no reviewed DOM transport classification.")]
    IStylePropertyMapReadOnlyIterator<global::Blazor.DOM.AdvancedTypes.StylePropertyMapReadOnlyReferenceTupleShape_5d666fed88> Entries() => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<IStylePropertyMapReadOnlyIterator<global::Blazor.DOM.AdvancedTypes.StylePropertyMapReadOnlyReferenceTupleShape_5d666fed88>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "entries", null, global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("StylePropertyMapReadOnlyIterator<[string, Iterable<CSSStyleValue>]>", "Named TypeScript type 'StylePropertyMapReadOnlyIterator' has no reviewed DOM transport classification.", nullable: false));

    [global::Microsoft.JSInterop.DomOperation("js:keys`0<>()[clr:]->IStylePropertyMapReadOnlyIterator<string>@transport:unsupported:False:False:False:StylePropertyMapReadOnlyIterator<string>", "keys", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "StylePropertyMapReadOnlyIterator<string>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'StylePropertyMapReadOnlyIterator' has no reviewed DOM transport classification.")]
    IStylePropertyMapReadOnlyIterator<string> Keys() => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<IStylePropertyMapReadOnlyIterator<string>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "keys", null, global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("StylePropertyMapReadOnlyIterator<string>", "Named TypeScript type 'StylePropertyMapReadOnlyIterator' has no reviewed DOM transport classification.", nullable: false));

    [global::Microsoft.JSInterop.DomOperation("js:values`0<>()[clr:]->IStylePropertyMapReadOnlyIterator<global::Microsoft.JSInterop.IBrowserIterable<ICSSStyleValue>>@transport:unsupported:False:False:False:StylePropertyMapReadOnlyIterator<Iterable<CSSStyleValue>>", "values", global::Microsoft.JSInterop.DomTransportKind.Unsupported, "StylePropertyMapReadOnlyIterator<Iterable<CSSStyleValue>>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false, UnsupportedReason = "Named TypeScript type 'StylePropertyMapReadOnlyIterator' has no reviewed DOM transport classification.")]
    IStylePropertyMapReadOnlyIterator<global::Microsoft.JSInterop.IBrowserIterable<ICSSStyleValue>> Values() => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<IStylePropertyMapReadOnlyIterator<global::Microsoft.JSInterop.IBrowserIterable<ICSSStyleValue>>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "values", null, global::Microsoft.JSInterop.DomTransportDescriptor.Unsupported("StylePropertyMapReadOnlyIterator<Iterable<CSSStyleValue>>", "Named TypeScript type 'StylePropertyMapReadOnlyIterator' has no reviewed DOM transport classification.", nullable: false));
}


public sealed class StylePropertyMapReadOnlyDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IStylePropertyMapReadOnly
{
}
