#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SVGAElement`** interface provides access to the properties of an a element, as well as methods to manipulate them.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGAElement)
/// </summary>
[global::Microsoft.JSInterop.DomEventTarget("SVGAElement", "SVGElementEventMap")]
public partial interface ISVGAElement : ISVGGraphicsElement, ISVGURIReference, global::Microsoft.JSInterop.IDomDispatchProxy
{
    [global::Microsoft.JSInterop.DomAccessor("rel", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
[global::Microsoft.JSInterop.DomAccessor("rel", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    string Rel
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<string>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "rel", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("string", nullable: false));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "rel", value);
    }

    [global::Microsoft.JSInterop.DomAccessor("relList", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "DOMTokenList", Nullable = false, Streamable = false, StructuredClone = false)]
    IDOMTokenList RelList
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<IDOMTokenList>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "relList", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("DOMTokenList", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// The **`SVGAElement.target`** read-only property of SVGAElement returns an SVGAnimatedString object that specifies the portion of a target window, frame, pane into which a document is to be opened when a link is activated.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGAElement/target)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("target", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedString", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedString Target
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedString>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "target", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedString", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>Sets the JavaScript property <c>relList</c> using its exact TypeScript setter type.</summary>
/// <param name="value">The value assigned to the JavaScript property.</param>
[global::Microsoft.JSInterop.DomAccessor("relList", global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "string", Nullable = false, Streamable = false, StructuredClone = true)]
    void SetRelList(string value) => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "relList", value);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener]);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener, bool capture) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, capture]);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,AddEventListenerOptions]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener, AddEventListenerOptions? options) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, options]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, bool capture) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, capture]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,EventListenerOptions]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, EventListenerOptions? options) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, options]);
}


public sealed class SVGAElementDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), ISVGAElement
{
}
