#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ISVGURIReference : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGAElement/href)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("href", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedString", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedString Href
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedString>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "href", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedString", nullable: false, streamable: false, structuredClone: false));
    }
}


public sealed class SVGURIReferenceDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), ISVGURIReference
{
}
