#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SVGFETurbulenceElement`** interface corresponds to the feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement)
/// </summary>
[global::Microsoft.JSInterop.DomEventTarget("SVGFETurbulenceElement", "SVGElementEventMap")]
public partial interface ISVGFETurbulenceElement : ISVGElement, ISVGFilterPrimitiveStandardAttributes, global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`baseFrequencyX`** read-only property of the SVGFETurbulenceElement interface reflects the X component of the baseFrequency attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/baseFrequencyX)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("baseFrequencyX", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedNumber", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedNumber BaseFrequencyX
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedNumber>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "baseFrequencyX", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedNumber", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// The **`baseFrequencyY`** read-only property of the SVGFETurbulenceElement interface reflects the Y component of the baseFrequency attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/baseFrequencyY)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("baseFrequencyY", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedNumber", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedNumber BaseFrequencyY
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedNumber>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "baseFrequencyY", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedNumber", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// The **`numOctaves`** read-only property of the SVGFETurbulenceElement interface reflects the numOctaves attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/numOctaves)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("numOctaves", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedInteger", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedInteger NumOctaves
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedInteger>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "numOctaves", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedInteger", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// The **`seed`** read-only property of the SVGFETurbulenceElement interface reflects the seed attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/seed)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("seed", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedNumber", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedNumber Seed
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedNumber>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "seed", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedNumber", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// The **`stitchTiles`** read-only property of the SVGFETurbulenceElement interface reflects the stitchTiles attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/stitchTiles)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("stitchTiles", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedEnumeration", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedEnumeration StitchTiles
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedEnumeration>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "stitchTiles", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedEnumeration", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// The **`type`** read-only property of the SVGFETurbulenceElement interface reflects the type attribute of the given feTurbulence element.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFETurbulenceElement/type)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("type", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedEnumeration", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedEnumeration Type
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedEnumeration>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "type", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedEnumeration", nullable: false, streamable: false, structuredClone: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("SVG_TURBULENCE_TYPE_UNKNOWN", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "0", Nullable = false, Streamable = false, StructuredClone = true)]
    double SVGTURBULENCETYPEUNKNOWN
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_TURBULENCE_TYPE_UNKNOWN", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("0", nullable: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("SVG_TURBULENCE_TYPE_FRACTALNOISE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "1", Nullable = false, Streamable = false, StructuredClone = true)]
    double SVGTURBULENCETYPEFRACTALNOISE
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_TURBULENCE_TYPE_FRACTALNOISE", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("1", nullable: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("SVG_TURBULENCE_TYPE_TURBULENCE", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "2", Nullable = false, Streamable = false, StructuredClone = true)]
    double SVGTURBULENCETYPETURBULENCE
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_TURBULENCE_TYPE_TURBULENCE", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("2", nullable: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("SVG_STITCHTYPE_UNKNOWN", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "0", Nullable = false, Streamable = false, StructuredClone = true)]
    double SVGSTITCHTYPEUNKNOWN
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_STITCHTYPE_UNKNOWN", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("0", nullable: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("SVG_STITCHTYPE_STITCH", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "1", Nullable = false, Streamable = false, StructuredClone = true)]
    double SVGSTITCHTYPESTITCH
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_STITCHTYPE_STITCH", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("1", nullable: false));
    }

    [global::Microsoft.JSInterop.DomAccessor("SVG_STITCHTYPE_NOSTITCH", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "2", Nullable = false, Streamable = false, StructuredClone = true)]
    double SVGSTITCHTYPENOSTITCH
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVG_STITCHTYPE_NOSTITCH", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("2", nullable: false));
    }

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener]);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener, bool capture) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, capture]);

    [global::Microsoft.JSInterop.DomOperation("js:addEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|AddEventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,AddEventListenerOptions]->void@transport:json-value:False:False:True:void", "addEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void AddEventListener(string type, EventListenerOrEventListenerObject listener, AddEventListenerOptions? options) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "addEventListener", [type, listener, options]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,bool]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, bool capture) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, capture]);

    [global::Microsoft.JSInterop.DomOperation("js:removeEventListener`0<>(StringKeyword:optional=False:rest=False,EventListenerOrEventListenerObject<>:optional=False:rest=False,union(BooleanKeyword|EventListenerOptions<>):optional=True:rest=False)[clr:string,EventListenerOrEventListenerObject,EventListenerOptions]->void@transport:json-value:False:False:True:void", "removeEventListener", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void RemoveEventListener(string type, EventListenerOrEventListenerObject listener, EventListenerOptions? options) => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeEventListener", [type, listener, options]);
}


public sealed class SVGFETurbulenceElementDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), ISVGFETurbulenceElement
{
}
