#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

/// <summary>
/// The **`SVGTransformList`** interface defines a list of SVGTransform objects.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList)
/// </summary>
public partial interface ISVGTransformList : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// The **`length`** read-only property of the SVGTransformList interface represents the number of items in the list.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/length)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("length", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    double Length
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "length", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false));
    }

    /// <summary>
/// The **`numberOfItems`** read-only property of the SVGTransformList interface represents the number of items in the list.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/numberOfItems)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("numberOfItems", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsonValue, "number", Nullable = false, Streamable = false, StructuredClone = true)]
    double NumberOfItems
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "numberOfItems", global::Microsoft.JSInterop.DomTransportDescriptor.JsonValue("number", nullable: false));
    }

    [global::Microsoft.JSInterop.DomIndexAccessor(global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomIndexKeyKind.Number, "number", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGTransform GetIndexedValueByNumber(double index) => global::Microsoft.JSInterop.WasmDomDispatch.GetIndex<ISVGTransform>((global::Microsoft.JSInterop.IDomDispatchProxy)this, index, global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGTransform", nullable: false, streamable: false, structuredClone: false));
[global::Microsoft.JSInterop.DomIndexAccessor(global::Microsoft.JSInterop.DomAccessorOperation.Set, global::Microsoft.JSInterop.DomIndexKeyKind.Number, "number", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform", Nullable = false, Streamable = false, StructuredClone = false)]
    void SetIndexedValueByNumber(double index, ISVGTransform value) => global::Microsoft.JSInterop.WasmDomDispatch.SetIndex((global::Microsoft.JSInterop.IDomDispatchProxy)this, index, value);

    /// <summary>
/// The `appendItem()` method of the SVGTransformList interface inserts a new item at the end of the list.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/appendItem)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:appendItem`0<>(SVGTransform<>:optional=False:rest=False)[clr:ISVGTransform]->ISVGTransform@transport:js-reference:False:False:False:SVGTransform", "appendItem", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    ISVGTransform AppendItem(ISVGTransform newItem) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<ISVGTransform>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "appendItem", [newItem], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGTransform", nullable: false, streamable: false, structuredClone: false));

    /// <summary>
/// The `clear()` method of the SVGTransformList interface clears all existing current items from the list, with the result being an empty list.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/clear)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:clear`0<>()[clr:]->void@transport:json-value:False:False:True:void", "clear", global::Microsoft.JSInterop.DomTransportKind.JsonValue, "void", Nullable = false, Promise = false, Streamable = false, StructuredClone = true)]
    void Clear() => global::Microsoft.JSInterop.WasmDomDispatch.InvokeVoid((global::Microsoft.JSInterop.IDomDispatchProxy)this, "clear", null);

    /// <summary>
/// The `consolidate()` method of the SVGTransformList interface consolidates the list of separate SVGTransform objects by multiplying the equivalent transformation matrices together to result in a list consisting of a single `SVGTransform` object of type `SVG_TRANSFORM_MATRIX`.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/consolidate)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:consolidate`0<>()[clr:]->ISVGTransform@transport:js-reference:True:False:False:SVGTransform | null", "consolidate", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform | null", Nullable = true, Promise = false, Streamable = false, StructuredClone = false)]
    ISVGTransform? Consolidate() => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<ISVGTransform?>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "consolidate", null, global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGTransform | null", nullable: true, streamable: false, structuredClone: false));

    /// <summary>
/// The `createSVGTransformFromMatrix()` method of the SVGTransformList interface creates an SVGTransform object which is initialized to a transform of type `SVG_TRANSFORM_MATRIX` and whose values are the given matrix.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/createSVGTransformFromMatrix)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:createSVGTransformFromMatrix`0<>(DOMMatrix2DInit<>:optional=True:rest=False)[clr:DOMMatrix2DInit]->ISVGTransform@transport:js-reference:False:False:False:SVGTransform", "createSVGTransformFromMatrix", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    ISVGTransform CreateSVGTransformFromMatrix(DOMMatrix2DInit? matrix = default) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<ISVGTransform>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "createSVGTransformFromMatrix", [matrix], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGTransform", nullable: false, streamable: false, structuredClone: false));

    /// <summary>
/// The `getItem()` method of the SVGTransformList interface returns the specified item from the list.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/getItem)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:getItem`0<>(NumberKeyword:optional=False:rest=False)[clr:double]->ISVGTransform@transport:js-reference:False:False:False:SVGTransform", "getItem", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    ISVGTransform GetItem(double index) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<ISVGTransform>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "getItem", [index], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGTransform", nullable: false, streamable: false, structuredClone: false));

    /// <summary>
/// The `initialize()` method of the SVGTransformList interface clears all existing current items from the list and re-initializes the list to hold the single item specified by the parameter.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/initialize)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:initialize`0<>(SVGTransform<>:optional=False:rest=False)[clr:ISVGTransform]->ISVGTransform@transport:js-reference:False:False:False:SVGTransform", "initialize", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    ISVGTransform Initialize(ISVGTransform newItem) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<ISVGTransform>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "initialize", [newItem], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGTransform", nullable: false, streamable: false, structuredClone: false));

    /// <summary>
/// The `insertItemBefore()` method of the SVGTransformList interface inserts a new item into the list at the specified position.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/insertItemBefore)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:insertItemBefore`0<>(SVGTransform<>:optional=False:rest=False,NumberKeyword:optional=False:rest=False)[clr:ISVGTransform,double]->ISVGTransform@transport:js-reference:False:False:False:SVGTransform", "insertItemBefore", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    ISVGTransform InsertItemBefore(ISVGTransform newItem, double index) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<ISVGTransform>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "insertItemBefore", [newItem, index], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGTransform", nullable: false, streamable: false, structuredClone: false));

    /// <summary>
/// The `removeItem()` method of the SVGTransformList interface removes an existing item from the list.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/removeItem)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:removeItem`0<>(NumberKeyword:optional=False:rest=False)[clr:double]->ISVGTransform@transport:js-reference:False:False:False:SVGTransform", "removeItem", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    ISVGTransform RemoveItem(double index) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<ISVGTransform>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "removeItem", [index], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGTransform", nullable: false, streamable: false, structuredClone: false));

    /// <summary>
/// The `replaceItem()` method of the SVGTransformList interface replaces an existing item in the list with a new item.
///
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGTransformList/replaceItem)
/// </summary>
[global::Microsoft.JSInterop.DomOperation("js:replaceItem`0<>(SVGTransform<>:optional=False:rest=False,NumberKeyword:optional=False:rest=False)[clr:ISVGTransform,double]->ISVGTransform@transport:js-reference:False:False:False:SVGTransform", "replaceItem", global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGTransform", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
    ISVGTransform ReplaceItem(ISVGTransform newItem, double index) => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<ISVGTransform>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "replaceItem", [newItem, index], global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGTransform", nullable: false, streamable: false, structuredClone: false));

    [global::Microsoft.JSInterop.DomOperation("js:Symbol.iterator`0<>()[clr:]->global::Microsoft.JSInterop.IBrowserIterableIterator<ISVGTransform>@transport:js-reference:False:False:False:ArrayIterator<SVGTransform>", "Symbol.iterator", global::Microsoft.JSInterop.DomTransportKind.JsReference, "ArrayIterator<SVGTransform>", Nullable = false, Promise = false, Streamable = false, StructuredClone = false)]
[global::Microsoft.JSInterop.DomSymbol(global::Microsoft.JSInterop.DomWellKnownSymbol.Iterator)]
    global::Microsoft.JSInterop.IBrowserIterableIterator<ISVGTransform> SymbolIterator() => global::Microsoft.JSInterop.WasmDomDispatch.Invoke<global::Microsoft.JSInterop.IBrowserIterableIterator<ISVGTransform>>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "Symbol.iterator", null, global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("ArrayIterator<SVGTransform>", nullable: false, streamable: false, structuredClone: false));
}


public sealed class SVGTransformListDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), ISVGTransformList
{
}
