#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ISVGFilterPrimitiveStandardAttributes : global::Microsoft.JSInterop.IDomDispatchProxy
{
    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFEBlendElement/height)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("height", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedLength", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedLength Height
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedLength>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "height", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedLength", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFEBlendElement/result)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("result", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedString", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedString Result
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedString>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "result", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedString", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFEBlendElement/width)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("width", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedLength", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedLength Width
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedLength>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "width", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedLength", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFEBlendElement/x)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("x", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedLength", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedLength X
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedLength>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "x", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedLength", nullable: false, streamable: false, structuredClone: false));
    }

    /// <summary>
/// [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGFEBlendElement/y)
/// </summary>
[global::Microsoft.JSInterop.DomAccessor("y", global::Microsoft.JSInterop.DomAccessorOperation.Get, global::Microsoft.JSInterop.DomTransportKind.JsReference, "SVGAnimatedLength", Nullable = false, Streamable = false, StructuredClone = false)]
    ISVGAnimatedLength Y
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedLength>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "y", global::Microsoft.JSInterop.DomTransportDescriptor.JsReference("SVGAnimatedLength", nullable: false, streamable: false, structuredClone: false));
    }
}


public sealed class SVGFilterPrimitiveStandardAttributesDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), ISVGFilterPrimitiveStandardAttributes
{
}
