#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ICSSMathValueFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    ICSSMathValue Prototype
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ICSSMathValue>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<ICSSMathValue>("prototype"));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value);
    }

    ICSSMathValue Create() => global::Microsoft.JSInterop.WasmDomDispatch.Construct<ICSSMathValue>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "CSSMathValue", null);
}


public sealed class CSSMathValueFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), ICSSMathValueFactory
{
}
