#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IHTMLTableColElementFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    IHTMLTableColElement Prototype
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<IHTMLTableColElement>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IHTMLTableColElement>("prototype"));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value);
    }

    IHTMLTableColElement Create() => global::Microsoft.JSInterop.WasmDomDispatch.Construct<IHTMLTableColElement>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "HTMLTableColElement", null);
}


public sealed class HTMLTableColElementFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IHTMLTableColElementFactory
{
}
