#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IMediaDeviceInfoFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    IMediaDeviceInfo Prototype
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<IMediaDeviceInfo>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IMediaDeviceInfo>("prototype"));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value);
    }

    IMediaDeviceInfo Create() => global::Microsoft.JSInterop.WasmDomDispatch.Construct<IMediaDeviceInfo>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "MediaDeviceInfo", null);
}


public sealed class MediaDeviceInfoFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IMediaDeviceInfoFactory
{
}
