#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IMediaErrorFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    IMediaError Prototype
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<IMediaError>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IMediaError>("prototype"));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value);
    }

    IMediaError Create() => global::Microsoft.JSInterop.WasmDomDispatch.Construct<IMediaError>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "MediaError", null);

    double MEDIAERRABORTED
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "MEDIA_ERR_ABORTED", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("MEDIA_ERR_ABORTED"));
    }

    double MEDIAERRNETWORK
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "MEDIA_ERR_NETWORK", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("MEDIA_ERR_NETWORK"));
    }

    double MEDIAERRDECODE
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "MEDIA_ERR_DECODE", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("MEDIA_ERR_DECODE"));
    }

    double MEDIAERRSRCNOTSUPPORTED
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<double>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "MEDIA_ERR_SRC_NOT_SUPPORTED", global::Microsoft.JSInterop.DomDispatch.InferTransport<double>("MEDIA_ERR_SRC_NOT_SUPPORTED"));
    }
}


public sealed class MediaErrorFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IMediaErrorFactory
{
}
