#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IMIDIOutputFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    IMIDIOutput Prototype
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<IMIDIOutput>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IMIDIOutput>("prototype"));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value);
    }

    IMIDIOutput Create() => global::Microsoft.JSInterop.WasmDomDispatch.Construct<IMIDIOutput>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "MIDIOutput", null);
}


public sealed class MIDIOutputFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IMIDIOutputFactory
{
}
