#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IPictureInPictureWindowFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    IPictureInPictureWindow Prototype
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<IPictureInPictureWindow>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IPictureInPictureWindow>("prototype"));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value);
    }

    IPictureInPictureWindow Create() => global::Microsoft.JSInterop.WasmDomDispatch.Construct<IPictureInPictureWindow>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "PictureInPictureWindow", null);
}


public sealed class PictureInPictureWindowFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IPictureInPictureWindowFactory
{
}
