#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IRTCIceCandidateFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    IRTCIceCandidate Prototype
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<IRTCIceCandidate>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IRTCIceCandidate>("prototype"));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value);
    }

    IRTCIceCandidate Create(RTCLocalIceCandidateInit? candidateInitDict = default) => global::Microsoft.JSInterop.WasmDomDispatch.Construct<IRTCIceCandidate>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "RTCIceCandidate", [candidateInitDict]);
}


public sealed class RTCIceCandidateFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IRTCIceCandidateFactory
{
}
