#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface ISVGAnimatedRectFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    ISVGAnimatedRect Prototype
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<ISVGAnimatedRect>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<ISVGAnimatedRect>("prototype"));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value);
    }

    ISVGAnimatedRect Create() => global::Microsoft.JSInterop.WasmDomDispatch.Construct<ISVGAnimatedRect>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "SVGAnimatedRect", null);
}


public sealed class SVGAnimatedRectFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), ISVGAnimatedRectFactory
{
}
