#nullable enable
// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

namespace Blazor.DOM;

public partial interface IXPathEvaluatorFactory : global::Microsoft.JSInterop.IDomDispatchProxy
{
    IXPathEvaluator Prototype
    {
        get => global::Microsoft.JSInterop.WasmDomDispatch.GetProperty<IXPathEvaluator>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", global::Microsoft.JSInterop.DomDispatch.InferTransport<IXPathEvaluator>("prototype"));
        set => global::Microsoft.JSInterop.WasmDomDispatch.SetProperty((global::Microsoft.JSInterop.IDomDispatchProxy)this, "prototype", value);
    }

    IXPathEvaluator Create() => global::Microsoft.JSInterop.WasmDomDispatch.Construct<IXPathEvaluator>((global::Microsoft.JSInterop.IDomDispatchProxy)this, "XPathEvaluator", null);
}


public sealed class XPathEvaluatorFactoryDomProxy(
    global::Microsoft.JSInterop.IJSObjectReference reference,
    global::Microsoft.JSInterop.IDomRuntime runtime,
    global::Microsoft.JSInterop.IDomProxyFactory factory)
    : global::Microsoft.JSInterop.WasmDomProxyBase(reference, runtime, factory), IXPathEvaluatorFactory
{
}
