// <auto-generated/>
// Generator : Blazor.DOM.CSharpGenerator v1.0.0
// Source    : data/Blazor.DOM (manifest-locked JSONL IR)
// Do not edit this file manually.
#nullable enable

using global::Microsoft.Extensions.DependencyInjection;

namespace Microsoft.JSInterop;

public static class GeneratedDomHost
{
    public static global::System.Threading.Tasks.ValueTask<global::Blazor.DOM.IWakeLock> GetWakeLockProxyAsync(
        this IBrowser browser, global::System.Threading.CancellationToken cancellationToken = default) =>
        browser.GetGlobalAsync<global::Blazor.DOM.IWakeLock>("navigator.wakeLock", cancellationToken);

    public static void RegisterProxies(IDomProxyFactory factory)
    {
        global::System.ArgumentNullException.ThrowIfNull(factory);
        factory.Register<global::Blazor.DOM.IEvent>((reference, runtime, owner) => new global::Blazor.DOM.EventDomProxy(reference, runtime, owner));
        factory.Register<global::Blazor.DOM.IEventFactory>((reference, runtime, owner) => new global::Blazor.DOM.EventFactoryDomProxy(reference, runtime, owner));
        factory.Register<global::Blazor.DOM.IEventListenerObject>((reference, runtime, owner) => new global::Blazor.DOM.EventListenerObjectDomProxy(reference, runtime, owner));
        factory.Register<global::Blazor.DOM.IEventTarget>((reference, runtime, owner) => new global::Blazor.DOM.EventTargetDomProxy(reference, runtime, owner));
        factory.Register<global::Blazor.DOM.IEventTargetFactory>((reference, runtime, owner) => new global::Blazor.DOM.EventTargetFactoryDomProxy(reference, runtime, owner));
        factory.Register<global::Blazor.DOM.IWakeLock>((reference, runtime, owner) => new global::Blazor.DOM.WakeLockDomProxy(reference, runtime, owner));
        factory.Register<global::Blazor.DOM.IWakeLockFactory>((reference, runtime, owner) => new global::Blazor.DOM.WakeLockFactoryDomProxy(reference, runtime, owner));
        factory.Register<global::Blazor.DOM.IWakeLockSentinel>((reference, runtime, owner) => new global::Blazor.DOM.WakeLockSentinelDomProxy(reference, runtime, owner));
        factory.Register<global::Blazor.DOM.IWakeLockSentinelFactory>((reference, runtime, owner) => new global::Blazor.DOM.WakeLockSentinelFactoryDomProxy(reference, runtime, owner));
    }
}

public interface IWakeLockCapability
{
    global::System.Threading.Tasks.ValueTask<global::Blazor.DOM.IWakeLock> GetWakeLockAsync(global::System.Threading.CancellationToken cancellationToken = default);
}

internal sealed class WakeLockCapability(IBrowser browser) : IWakeLockCapability
{
    public global::System.Threading.Tasks.ValueTask<global::Blazor.DOM.IWakeLock> GetWakeLockAsync(global::System.Threading.CancellationToken cancellationToken = default) =>
        browser.GetGlobalAsync<global::Blazor.DOM.IWakeLock>("navigator.wakeLock", cancellationToken);

}

public static class WakeLockCapabilityMetadata
{
    public const bool RequiresSecureContext = true;
    public const bool RequiresUserActivation = false;
    public static global::System.Collections.Generic.IReadOnlyList<string> Features { get; } =
        ["screen-wake-lock"];
    public static global::System.Collections.Generic.IReadOnlyList<string> FeatureDetectionPaths { get; } =
        ["navigator.wakeLock"];
}

public static class WakeLockCapabilityServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddWakeLockCapability(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        global::System.ArgumentNullException.ThrowIfNull(services);
        services.AddScoped<ServerDomRuntime>();
        services.AddScoped<IDomRuntime>(static provider => provider.GetRequiredService<ServerDomRuntime>());
        services.AddScoped<IDomProxyFactory>(static provider =>
        {
            var factory = new DomProxyFactory(provider.GetRequiredService<IDomRuntime>());
            GeneratedDomHost.RegisterProxies(factory);
            return factory;
        });
        services.AddScoped<IBrowser, ServerBrowser>();
        services.AddScoped<IWakeLockCapability, WakeLockCapability>();
        return services;
    }
}
